import type { Winery } from "@/lib/types";

// Châteaux-ícone de Bordeaux — metadados leves (sem o dossiê pesado).
// Gerado de research/bordeaux-chateaux-premium/. Fotos são placeholders REAIS,
// trocáveis no painel (nunca IA). O dossiê completo vive em ./chateaux-dossiers
// e só é carregado na página de detalhe da vinícola.
export const iconicChateaux: Winery[] = [
  {
    slug: "chateau-margaux",
    name: "Château Margaux",
    appellation: "Médoc, Margaux AOC",
    classification: "Premier Grand Cru Classé 1855",
    family: "Família Mentzelopoulos",
    region: "Médoc, Margaux AOC",
    heroImage: "/photos/hero-margaux.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-mouton-rothschild",
    name: "Château Mouton Rothschild",
    appellation: "Médoc, Pauillac AOC",
    classification: "Premier Grand Cru Classé 1855 desde a promoção de 1973",
    family: "Família Rothschild / Baron Philippe de Rothschild S.A.",
    region: "Médoc, Pauillac AOC",
    heroImage: "/photos/hero-lafite.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-lafite-rothschild",
    name: "Château Lafite Rothschild",
    appellation: "Médoc, Pauillac AOC",
    classification: "Premier Grand Cru Classé 1855",
    family: "Domaines Barons de Rothschild Lafite",
    region: "Médoc, Pauillac AOC",
    heroImage: "/photos/hero-lafite.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-d-yquem",
    name: "Château d'Yquem",
    appellation: "Sauternais, Sauternes AOC",
    classification: "Premier Cru Supérieur 1855, categoria única",
    family: "LVMH",
    region: "Sauternais, Sauternes AOC",
    heroImage: "/photos/hero-vignoble.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-haut-brion",
    name: "Château Haut-Brion",
    appellation: "Graves, Pessac-Léognan AOC",
    classification: "Premier Grand Cru Classé 1855; Cru Classé de Graves",
    family: "Domaine Clarence Dillon",
    region: "Graves, Pessac-Léognan AOC",
    heroImage: "/photos/hero-medoc.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-cheval-blanc",
    name: "Château Cheval Blanc",
    appellation: "Saint-Émilion, Saint-Émilion Grand Cru AOC",
    classification: "Premier Grand Cru Classé A em classificações históricas de Saint-Émilion; retirou-se da classificação de 2022",
    family: "LVMH e família Frère",
    region: "Saint-Émilion, Saint-Émilion Grand Cru AOC",
    heroImage: "/photos/hero-saint-emilion.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-ausone",
    name: "Château Ausone",
    appellation: "Saint-Émilion, Saint-Émilion Grand Cru AOC",
    classification: "Premier Grand Cru Classé A em classificações históricas; retirou-se da classificação de 2022",
    family: "Família Vauthier",
    region: "Saint-Émilion, Saint-Émilion Grand Cru AOC",
    heroImage: "/photos/hero-saint-emilion.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-latour",
    name: "Château Latour",
    appellation: "Médoc, Pauillac AOC",
    classification: "Premier Grand Cru Classé 1855",
    family: "Groupe Artémis / François Pinault",
    region: "Médoc, Pauillac AOC",
    heroImage: "/photos/hero-lafite.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-palmer",
    name: "Château Palmer",
    appellation: "Médoc, Margaux AOC",
    classification: "Troisième Grand Cru Classé 1855",
    family: "Famílias Sichel e Mähler-Besse e demais acionistas",
    region: "Médoc, Margaux AOC",
    heroImage: "/photos/hero-margaux.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-la-fleur-petrus",
    name: "Château La Fleur-Pétrus",
    appellation: "Pomerol AOC",
    classification: "Pomerol não possui classificação oficial",
    family: "Família Moueix / Ets. Jean-Pierre Moueix",
    region: "Pomerol AOC",
    heroImage: "/photos/hero-saint-emilion.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-smith-haut-lafitte",
    name: "Château Smith Haut Lafitte",
    appellation: "Graves, Pessac-Léognan AOC",
    classification: "Cru Classé de Graves",
    family: "Família Cathiard",
    region: "Graves, Pessac-Léognan AOC",
    heroImage: "/photos/hero-medoc.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-beychevelle",
    name: "Château Beychevelle",
    appellation: "Médoc, Saint-Julien AOC",
    classification: "Quatrième Grand Cru Classé 1855",
    family: "Grands Millésimes de France, com Castel e Suntory",
    region: "Médoc, Saint-Julien AOC",
    heroImage: "/photos/hero-lafite.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-pichon-baron",
    name: "Château Pichon Baron",
    appellation: "Médoc, Pauillac AOC",
    classification: "Deuxième Grand Cru Classé 1855",
    family: "AXA Millésimes",
    region: "Médoc, Pauillac AOC",
    heroImage: "/photos/hero-lafite.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-lynch-bages",
    name: "Château Lynch-Bages",
    appellation: "Médoc, Pauillac AOC",
    classification: "Cinquième Grand Cru Classé 1855",
    family: "Família Cazes",
    region: "Médoc, Pauillac AOC",
    heroImage: "/photos/hero-lafite.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-canon",
    name: "Château Canon",
    appellation: "Saint-Émilion Grand Cru AOC",
    classification: "Premier Grand Cru Classé B na classificação de Saint-Émilion 2022",
    family: "Chanel / Wertheimer",
    region: "Saint-Émilion Grand Cru AOC",
    heroImage: "/photos/hero-saint-emilion.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-cos-d-estournel",
    name: "Château Cos d'Estournel",
    appellation: "Médoc, Saint-Estèphe AOC",
    classification: "Deuxième Grand Cru Classé 1855",
    family: "Michel Reybier",
    region: "Médoc, Saint-Estèphe AOC",
    heroImage: "/photos/hero-lafite.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-troplong-mondot",
    name: "Château Troplong Mondot",
    appellation: "Saint-Émilion Grand Cru AOC",
    classification: "Premier Grand Cru Classé B",
    family: "SCOR",
    region: "Saint-Émilion Grand Cru AOC",
    heroImage: "/photos/hero-saint-emilion.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-pape-clement",
    name: "Château Pape Clément",
    appellation: "Graves, Pessac-Léognan AOC",
    classification: "Cru Classé de Graves",
    family: "Bernard Magrez",
    region: "Graves, Pessac-Léognan AOC",
    heroImage: "/photos/hero-medoc.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-la-dominique",
    name: "Château La Dominique",
    appellation: "Saint-Émilion Grand Cru AOC",
    classification: "Grand Cru Classé de Saint-Émilion",
    family: "Família Fayat",
    region: "Saint-Émilion Grand Cru AOC",
    heroImage: "/photos/hero-saint-emilion.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-guiraud",
    name: "Château Guiraud",
    appellation: "Sauternes AOC",
    classification: "Premier Grand Cru Classé 1855",
    family: "Matthieu Gufflet e parceiros conforme estrutura atual",
    region: "Sauternes AOC",
    heroImage: "/photos/hero-vignoble.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
];
