import type { Winery } from "@/lib/types";

// Châteaux-ícone de Bordeaux — metadados leves (sem o dossiê pesado).
// Gerado de research/bordeaux-chateaux-premium/. Fotos são placeholders REAIS,
// trocáveis no painel (nunca IA). O dossiê completo vive em ./chateaux-dossiers
// e só é carregado na página de detalhe da vinícola.
export const iconicChateaux: Winery[] = [
  {
    slug: "chateau-margaux",
    name: "Château Margaux",
    appellation: "Médoc, Margaux AOC",
    classification: "Premier Grand Cru Classé 1855",
    family: "Família Mentzelopoulos",
    region: "Médoc, Margaux AOC",
    heroImage: "https://framerusercontent.com/assets/NrmSAGR3eetbhhi5ciounZb7vk.webp",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-mouton-rothschild",
    name: "Château Mouton Rothschild",
    appellation: "Médoc, Pauillac AOC",
    classification: "Premier Grand Cru Classé 1855 desde a promoção de 1973",
    family: "Família Rothschild / Baron Philippe de Rothschild S.A.",
    region: "Médoc, Pauillac AOC",
    heroImage: "https://www.chateau-mouton-rothschild.com/cellar/uploads/Chateau_Mouton_Rothschild_vue_des_vignes_1440.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-lafite-rothschild",
    name: "Château Lafite Rothschild",
    appellation: "Médoc, Pauillac AOC",
    classification: "Premier Grand Cru Classé 1855",
    family: "Domaines Barons de Rothschild Lafite",
    region: "Médoc, Pauillac AOC",
    heroImage: "https://www.ungerweine.de/_contello/i/1a86d694-7423-4b95-9467-8f56a8080686.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-d-yquem",
    name: "Château d'Yquem",
    appellation: "Sauternais, Sauternes AOC",
    classification: "Premier Cru Supérieur 1855, categoria única",
    family: "LVMH",
    region: "Sauternais, Sauternes AOC",
    heroImage: "https://www.yquem.fr/assets/og--ksNZ63V.jpeg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-haut-brion",
    name: "Château Haut-Brion",
    appellation: "Graves, Pessac-Léognan AOC",
    classification: "Premier Grand Cru Classé 1855; Cru Classé de Graves",
    family: "Domaine Clarence Dillon",
    region: "Graves, Pessac-Léognan AOC",
    heroImage: "https://www.haut-brion.com/wp-content/uploads/sites/3/2022/04/bkg-hb-home-min.png",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-cheval-blanc",
    name: "Château Cheval Blanc",
    appellation: "Saint-Émilion, Saint-Émilion Grand Cru AOC",
    classification: "Premier Grand Cru Classé A em classificações históricas de Saint-Émilion; retirou-se da classificação de 2022",
    family: "LVMH e família Frère",
    region: "Saint-Émilion, Saint-Émilion Grand Cru AOC",
    heroImage: "https://www.chateau-cheval-blanc.com/wp-content/uploads/2023/11/chateau-cheval-blanc-le-petit-cheval-la-vignoble.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-ausone",
    name: "Château Ausone",
    appellation: "Saint-Émilion, Saint-Émilion Grand Cru AOC",
    classification: "Premier Grand Cru Classé A em classificações históricas; retirou-se da classificação de 2022",
    family: "Família Vauthier",
    region: "Saint-Émilion, Saint-Émilion Grand Cru AOC",
    heroImage: "https://www.ungerweine.de/_contello/i/1bb391be-d89b-4719-8c7e-ee53d8728b4c.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-latour",
    name: "Château Latour",
    appellation: "Médoc, Pauillac AOC",
    classification: "Premier Grand Cru Classé 1855",
    family: "Groupe Artémis / François Pinault",
    region: "Médoc, Pauillac AOC",
    heroImage: "https://www.chateau-latour.com/assets/public/img/social/affiche-facebook.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-palmer",
    name: "Château Palmer",
    appellation: "Médoc, Margaux AOC",
    classification: "Troisième Grand Cru Classé 1855",
    family: "Famílias Sichel e Mähler-Besse e demais acionistas",
    region: "Médoc, Margaux AOC",
    heroImage: "https://cdn.prod.website-files.com/63a417a748979747a3239e66/63ef64b43229e5eae4466149_chateaupalmer-OG-image.png",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-la-fleur-petrus",
    name: "Château La Fleur-Pétrus",
    appellation: "Pomerol AOC",
    classification: "Pomerol não possui classificação oficial",
    family: "Família Moueix / Ets. Jean-Pierre Moueix",
    region: "Pomerol AOC",
    heroImage: "https://www.moueix.com/sites/default/files/styles/hero_1280x1280/public/2021-07/slider_daccueil_photo_chai.jpg?itok=aF4MnGCU",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-smith-haut-lafitte",
    name: "Château Smith Haut Lafitte",
    appellation: "Graves, Pessac-Léognan AOC",
    classification: "Cru Classé de Graves",
    family: "Família Cathiard",
    region: "Graves, Pessac-Léognan AOC",
    heroImage: "https://www.smith-haut-lafitte.com/wp-content/uploads/2021/04/chateau-smith-haut-lafitte-yem.png",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-beychevelle",
    name: "Château Beychevelle",
    appellation: "Médoc, Saint-Julien AOC",
    classification: "Quatrième Grand Cru Classé 1855",
    family: "Grands Millésimes de France, com Castel e Suntory",
    region: "Médoc, Saint-Julien AOC",
    heroImage: "https://www.beychevelle.com/wp-content/uploads/2025/09/PAGE-ACCEUIL-TERROIR-1-scaled.webp",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-pichon-baron",
    name: "Château Pichon Baron",
    appellation: "Médoc, Pauillac AOC",
    classification: "Deuxième Grand Cru Classé 1855",
    family: "AXA Millésimes",
    region: "Médoc, Pauillac AOC",
    heroImage: "https://www.pichonbaron.com/image/images_site/1/accueil-background-site.jpg?1782288937",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-lynch-bages",
    name: "Château Lynch-Bages",
    appellation: "Médoc, Pauillac AOC",
    classification: "Cinquième Grand Cru Classé 1855",
    family: "Família Cazes",
    region: "Médoc, Pauillac AOC",
    heroImage: "https://www.lynchbages.com/wp-content/uploads/2022/01/hero-scaled.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-canon",
    name: "Château Canon",
    appellation: "Saint-Émilion Grand Cru AOC",
    classification: "Premier Grand Cru Classé B na classificação de Saint-Émilion 2022",
    family: "Chanel / Wertheimer",
    region: "Saint-Émilion Grand Cru AOC",
    heroImage: "https://sothebys-md.brightspotcdn.com/dims4/default/c340910/2147483647/strip/true/crop/1920x1282+0+0/resize/4096x2735!/quality/90/?url=http%3A%2F%2Fsothebys-brightspot.s3.amazonaws.com%2Fmedia-desk%2F4b%2Fa7%2Fcb6891ff4a47ac79c7b7464c35f6%2F20-chateaucanon-lechateau-3-hd-1.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-cos-d-estournel",
    name: "Château Cos d'Estournel",
    appellation: "Médoc, Saint-Estèphe AOC",
    classification: "Deuxième Grand Cru Classé 1855",
    family: "Michel Reybier",
    region: "Médoc, Saint-Estèphe AOC",
    heroImage: "https://www.estournel.com/wp-content/uploads/2025/05/Cos-dEstournel-Second-Cru-Classe-en-1855-a-Saint-Estephe.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-troplong-mondot",
    name: "Château Troplong Mondot",
    appellation: "Saint-Émilion Grand Cru AOC",
    classification: "Premier Grand Cru Classé B",
    family: "SCOR",
    region: "Saint-Émilion Grand Cru AOC",
    heroImage: "https://www.troplong-mondot.com/media/site/93f4ce00cb-1756717017/accueil-chateau-troplong-mondot-1440x-q90.webp",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-pape-clement",
    name: "Château Pape Clément",
    appellation: "Graves, Pessac-Léognan AOC",
    classification: "Cru Classé de Graves",
    family: "Bernard Magrez",
    region: "Graves, Pessac-Léognan AOC",
    heroImage: "https://lapetitecave.net/wp-content/uploads/2024/11/chateau-pape-clement.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-la-dominique",
    name: "Château La Dominique",
    appellation: "Saint-Émilion Grand Cru AOC",
    classification: "Grand Cru Classé de Saint-Émilion",
    family: "Família Fayat",
    region: "Saint-Émilion Grand Cru AOC",
    heroImage: "https://www.saint-emilion-tourisme.com/uploads/img/chateau-la-dominique-sd-15-07-2401826-671f6278b4780551353219__68ff99dfbf0f6.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
  {
    slug: "chateau-guiraud",
    name: "Château Guiraud",
    appellation: "Sauternes AOC",
    classification: "Premier Grand Cru Classé 1855",
    family: "Matthieu Gufflet e parceiros conforme estrutura atual",
    region: "Sauternes AOC",
    heroImage: "https://www.chateauguiraud.com/media/cache/jadro_resize/rc/VaYCckvb1745923292/jadroRoot/medias/649c063c8c7be/chateau-guiraud-1er-grand-cru-classe-en-1855-3-min.jpg",
    grapes: [],
    icons: [],
    history: "",
    qimoSelect: true,
  },
];
