import type { ChefExperience, ChefProfile } from "@/lib/types";

export const chefProfile: ChefProfile = {
  slug: "thomas-troisgros",
  name: "Thomas Troisgros",
  kicker: "Sobre o chef",
  title: "Thomas Troisgros",
  lead:
    "Herdeiro da quarta geração Troisgros, Thomas traduz a técnica francesa da família em uma cozinha contemporânea, brasileira e autoral. No Rio, está à frente do Oseille, restaurante intimista de menu-degustação reconhecido com uma estrela Michelin.",
  body:
    "Sua trajetória passa pelo Culinary Institute of America, por Daniel Boulud em Nova York e por casas de referência como Mugaritz e Arzak, antes de assumir projetos da família no Brasil e criar seus próprios restaurantes.",
  closingQuote:
    "A curadoria QIMO nasce desse encontro: precisão francesa, alma carioca e uma leitura de Bordeaux feita para poucos convidados.",
  michelinLabel: "1 estrela Michelin",
  michelinText: "Chef à frente do Oseille, no Rio de Janeiro, reconhecido pelo Guia Michelin com uma estrela.",
  hotListLabel: "Hot List 2024",
  hotListText: "Oseille foi destacado pela Condé Nast Traveler entre os melhores novos restaurantes do mundo em 2024.",
  bestChefLabel: "The Best Chef Awards",
  bestChefText: "Thomas recebeu a distinção One Knife, categoria Excellent, no The Best Chef Awards.",
  fiftyBestLabel: "50 Best",
  fiftyBestText: "O Olympe, onde Thomas consolidou sua cozinha autoral, figurou em edições do Latin America's 50 Best Restaurants.",
  lineageLabel: "Dinastia Troisgros",
  lineageText: "Quarta geração de uma família que marcou a nouvelle cuisine e mantém três estrelas Michelin na França desde 1968.",
};

// Seção "Chef" — experiências extras de gastronomia (cross-sell), com curadoria de
// Thomas Troisgros. Conteúdo inicial editável no painel (aba Conteúdo → "Chef").
// Preços "sob consulta" até definição comercial. Apenas fotografias reais.
export const chefExperiences: ChefExperience[] = [
  {
    slug: "noite-vinhas-iconicas-haut-brion",
    name: "Jantar de gala no Château Haut-Brion",
    category: "Château Haut-Brion · Noite exclusiva",
    chef: "Chef Andrea Capasso · Le Clarence (2★ Michelin)",
    heroImage: "/media/haut-brion-v2-jantar.jpg",
    gallery: [
      "/media/haut-brion-v2-jantar.jpg",
      "/media/haut-brion-v2-salao.jpg",
      "/media/haut-brion-v2-vinhos.jpg",
      "/media/haut-brion-v2-la-mission.jpg",
      "/media/haut-brion-v2-cave.jpg",
    ],
    tagline: "Entre as vinhas mais lendárias de Bordeaux — patrimônio, alta gastronomia e Grands Crus.",
    description:
      "No Pavillon Catelan, elo histórico entre o Château Haut-Brion e o Château La Mission Haut-Brion, uma experiência que reúne patrimônio e grandes vinhos. Começa com um tour privativo por um dos châteaux e uma recepção com champanhe no terraço, sobre os vinhedos icônicos do Haut-Brion. Em seguida, um menu-degustação assinado pelo chef Andrea Capasso (Le Clarence, duas estrelas Michelin), com cada tempo harmonizado a vinhos das propriedades. Pode se estender com música na cave abobadada restaurada e um presente comemorativo na despedida. A experiência se confirma com um mínimo de 35 participantes (até 50 lugares).",
    highlights: [
      "Tour privativo pelo Château Haut-Brion ou La Mission Haut-Brion",
      "Recepção com champanhe no terraço sobre os vinhedos",
      "Jantar em quatro tempos do chef Andrea Capasso (2★ Michelin)",
      "Harmonização com vinhos das propriedades (Haut-Brion, La Clarté, Quintus)",
      "Wine Ambassador comentando cada rótulo da noite",
      "Cave abobadada para dançar e presente comemorativo",
    ],
    duration: "19h às 1h",
    price: "€ 850 por pessoa",
    qimoSelect: true,
  },
  {
    slug: "chateau-yquem-visita-privada",
    name: "Château d'Yquem — visita e degustação privada",
    category: "Château d'Yquem · Private Experience",
    chef: "Anfitrião Pierre Lurton · diretor do Château d'Yquem e do Cheval Blanc",
    heroImage: "/media/yquem-fachada.jpg",
    gallery: [
      "/media/yquem-fachada.jpg",
      "/media/yquem-aereo.jpg",
      "/media/yquem-escada.jpg",
      "/media/yquem-jefferson.jpg",
      "/media/yquem-adega.jpg",
      "/media/yquem-janela.jpg",
      "/media/yquem-sala-degustacao.jpg",
      "/media/yquem-decanter.jpg",
      "/media/yquem-taca.jpg",
      "/media/yquem-patio.jpg",
    ],
    tagline: "Portas que normalmente não se abrem — um Yquem de acesso reservado.",
    description:
      "Uma tarde no Château d'Yquem conduzida pessoalmente por Pierre Lurton, diretor do Château d'Yquem e do Château Cheval Blanc, um dos nomes mais respeitados de Bordeaux. Saída às 14h em vans privativas Cadillac rumo a Sauternes, para percorrer jardins, vinhedos e adegas de uma das propriedades mais lendárias do mundo. O roteiro inclui acesso privado ao interior do château e à cave histórica particular, normalmente fechados às visitas, e a chance de ver de perto relíquias como um Yquem do século XVIII associado a Thomas Jefferson e o decanter de cristal da família imperial russa. A degustação reúne três safras de Château d'Yquem — 2016, 2010 e 2006 — harmonizadas com aperitivos e foie gras, e encerra ao pôr do sol no pátio murado do château, reservado para o brinde ao fim da tarde, diante dos vinhedos. Não é apenas visitar o Château d'Yquem: é acessar um Yquem que normalmente permanece atrás de portas fechadas.",
    highlights: [
      "Visita conduzida por Pierre Lurton, diretor de Yquem e Cheval Blanc",
      "Saída às 14h em vans privativas Cadillac",
      "Acesso privado ao interior do château e à cave histórica de mais de três séculos",
      "A relíquia: um Yquem do século XVIII gravado com as iniciais de Thomas Jefferson",
      "Degustação de três safras — 2016, 2010 e 2006 — com aperitivos e foie gras",
      "Pôr do sol no pátio murado, diante dos vinhedos",
    ],
    duration: "Tarde inteira · a partir das 14h",
    price: "€ 400 por pessoa · 20 lugares apenas",
    qimoSelect: true,
    reserva: { vagas: 20, dia: 3, horario: "14:00" },
  },
  {
    slug: "soiree-chateau-marjosse",
    name: "QIMO Soirée Château Marjosse",
    category: "Château Marjosse · Soirée privativa",
    chef: "Thomas Troisgros · anfitriões Alê Forbes e Pierre Lurton",
    heroImage: "/media/marjosse-fachada.jpg",
    gallery: [
      "/media/marjosse-fachada.jpg",
      "/media/marjosse-mesa-jardim.jpg",
      "/media/marjosse-salao-jantar.jpg",
      "/media/marjosse-sunset.jpg",
      "/media/marjosse-jardim-jantar.jpg",
      "/media/marjosse-hall.jpg",
      "/media/marjosse-cozinha-antiga.jpg",
      "/media/marjosse-adega.jpg",
      "/media/marjosse-cheval-blanc.jpg",
      "/media/marjosse-anfitrioes.jpg",
    ],
    tagline: "Do sunset ao sunrise — uma noite na casa de família de Alê Forbes e Pierre Lurton.",
    description:
      "Há lugares que se visitam — e há lugares cujas portas só se abrem para convidados. Construído em 1788 e normalmente fechado ao público, o Château Marjosse é a propriedade e residência de família de Alê Forbes e Pierre Lurton, no coração de Bordeaux, entre parcelas de vinhas velhas e floresta. Para uma soirée criada especialmente para a QIMO, a casa abre suas portas. A noite começa com um apéro ao ar livre diante dos vinhedos, com vinhos da cave privativa dos anfitriões — da Champagne safrada à Cuvée Palombe, a mais premiada de Marjosse. No sunset, Pierre Rolley, maître fromager, conduz uma degustação de queijos maturados para a ocasião, enquanto Thomas Troisgros cuida dos aperitivos, com ostras de Arcachon e caviar local. O jantar segue no salão histórico, assinado por Thomas Troisgros, com harmonização escolhida a dedo por Alê — e, com o prato principal, a abertura de uma raríssima garrafa de Château Cheval Blanc. Depois, muda o ritmo: queijos, sobremesas do chef e digestivos premium, o DJ LP assume a música e dança-se sob as estrelas, sem hora para terminar.",
    highlights: [
      "Casa de família de Alê Forbes e Pierre Lurton, de 1788, fechada ao público",
      "Jantar assinado por Thomas Troisgros no salão histórico",
      "Apéro com vinhos da cave privativa (Champagne safrada e Cuvée Palombe)",
      "Queijos maturados com o maître fromager + ostras de Arcachon e caviar",
      "Uma raríssima garrafa de Château Cheval Blanc no prato principal",
      "After sob as estrelas com o DJ LP, sem hora para terminar",
    ],
    duration: "A partir das 17h · do sunset ao sunrise",
    price: "€ 600 por pessoa · até 50 convidados",
    qimoSelect: true,
    reserva: { vagas: 50, dia: 4, horario: "17:00" },
  },
  {
    slug: "jantar-troisgros-a-bordo",
    name: "Jantar assinado Thomas Troisgros",
    category: "Jantar exclusivo",
    chef: "Thomas Troisgros",
    heroImage: "/photos/ship-dining.jpg",
    gallery: [
      "/photos/ship-dining.jpg",
      "/photos/food-foiegras.jpg",
      "/photos/food-magret.jpg",
      "/photos/wine-glass.jpg",
    ],
    tagline: "Uma noite única a bordo — a mesa mais concorrida da viagem.",
    description:
      "Uma noite à parte a bordo: menu-degustação criado por Thomas Troisgros, unindo a técnica francesa ao olhar brasileiro, com harmonização de Grands Crus selecionados. Número reduzido de convidados.",
    highlights: [
      "Menu-degustação exclusivo do chef",
      "Harmonização com Grands Crus de Bordeaux",
      "Lugares limitados — ambiente intimista",
      "Apresentação do chef a cada tempo",
    ],
    duration: "≈ 3 horas",
    price: "sob consulta",
    qimoSelect: true,
  },
  {
    slug: "aula-cozinha-franco-brasileira",
    name: "Aula de cozinha franco-brasileira",
    category: "Experiência hands-on",
    chef: "Thomas Troisgros",
    heroImage: "/photos/food-entrecote.jpg",
    gallery: [
      "/photos/food-mercado.jpg",
      "/photos/food-entrecote.jpg",
      "/photos/food-ostras.jpg",
      "/photos/food-queijos.jpg",
    ],
    tagline: "Cozinhe ao lado do chef — e leve a técnica para casa.",
    description:
      "Mão na massa com a curadoria do chef: técnicas, produtos do mercado local de Bordeaux e o diálogo entre as duas cozinhas. Encerramento com almoço harmonizado.",
    highlights: [
      "Aula prática guiada pelo chef",
      "Ingredientes do mercado local de Bordeaux",
      "Almoço harmonizado ao final",
      "Grupo pequeno, atenção individual",
    ],
    duration: "≈ 2h30",
    price: "sob consulta",
    qimoSelect: true,
  },
  {
    slug: "harmonizacao-bordeaux-brasil",
    name: "Harmonização Bordeaux & Brasil",
    category: "Degustação guiada",
    chef: "Thomas Troisgros",
    heroImage: "/photos/wine-glass.jpg",
    gallery: [
      "/photos/wine-glass.jpg",
      "/photos/wine-graves.jpg",
      "/photos/wine-pomerol.jpg",
      "/photos/food-queijos.jpg",
    ],
    tagline: "Encontros improváveis entre o vinho francês e o Brasil.",
    description:
      "Uma degustação conduzida em torno de encontros improváveis entre vinhos de Bordeaux e ingredientes brasileiros — uma viagem sensorial curada a quatro mãos.",
    highlights: [
      "Vinhos de Bordeaux selecionados",
      "Petiscos autorais de inspiração brasileira",
      "Condução comentada, do rótulo à taça",
      "Experiência sensorial curada a quatro mãos",
    ],
    duration: "≈ 1h30",
    price: "sob consulta",
    qimoSelect: false,
  },
];
