import type { City } from "@/lib/types";

export const cities: City[] = [
  {
    slug: "bordeaux",
    name: "Bordeaux",
    region: "Gironde · Nova Aquitânia",
    tagline: "A Bela Adormecida que despertou em pedra dourada",
    heroImage: "https://www.travelonatimebudget.co.uk/wp-content/uploads/2023/03/Place-de-la-Bourse-Bordeaux.jpg",
    history:
      "Porto romano fundado como Burdigala, Bordeaux enriqueceu com o comércio de vinho a partir da Idade Média, quando esteve sob domínio inglês por três séculos. O século XVIII lhe deu sua feição atual: uma cidade de fachadas de pedra calcária clara, alinhadas ao longo do rio Garonne em forma de meia-lua — o 'Port de la Lune'. Todo o centro histórico é Patrimônio Mundial da UNESCO, o maior conjunto urbano do mundo com essa distinção.",
    curiosities: [
      "O Miroir d'Eau, em frente à Place de la Bourse, é o maior espelho d'água do mundo — uma lâmina de 2 cm que reflete o casario.",
      "Por muito tempo as fachadas ficaram escuras de fuligem; uma grande limpeza revelou a pedra loira que rendeu o apelido 'a bela adormecida'.",
      "A Cité du Vin, museu do vinho, tem arquitetura que evoca o vinho girando na taça.",
    ],
    toDo: [
      "Place de la Bourse e o Miroir d'Eau ao entardecer",
      "Passeio pelos cais reabilitados (Quais)",
      "Grosse Cloche e a rua Sainte-Catherine",
      "Basilique Saint-Michel e a torre",
      "Bassins des Lumières — arte digital imersiva",
    ],
    photoSpots: [
      "Place de la Bourse refletida no Miroir d'Eau",
      "Pont de Pierre ao amanhecer",
      "Rue Notre-Dame no bairro dos Chartrons",
    ],
    bestTimes: "Fim de tarde para a luz dourada nas fachadas; manhã cedo nos cais, sem multidão.",
    restaurants: [
      "Le Pressoir d'Argent — Gordon Ramsay (2 estrelas Michelin, InterContinental)",
      "La Tupina (cozinha do Sudoeste)",
      "Le Chapon Fin (histórico, desde 1825)",
    ],
    cafes: ["Café Napoléon", "Karl (Place du Parlement)"],
    shops: ["Rue Sainte-Catherine", "Galeries Bordelaises", "Bairro des Chartrons (antiquários)"],
    localWines: ["Bordeaux AOC", "Bordeaux Supérieur", "Crémant de Bordeaux"],
    coords: { lat: 44.8378, lng: -0.5792 },
    visitedOnDays: [1, 6, 7, 8],
  },
  {
    slug: "pauillac",
    name: "Pauillac",
    region: "Médoc · Margem esquerda",
    tagline: "A capital mundial do Cabernet Sauvignon",
    heroImage: "https://www.guide-bordeaux-gironde.com/_bibli/articlesPage/236/images/facede-fluviale-de-pauillac.jpg?v=preload",
    history:
      "Pequena cidade portuária às margens do Gironde, Pauillac é o coração do Médoc e detém uma concentração de prestígio sem paralelo: três dos cinco Premiers Grands Crus Classés de 1855 — Lafite Rothschild, Latour e Mouton Rothschild — nascem em seu solo de cascalho. É o terroir por excelência do Cabernet Sauvignon.",
    curiosities: [
      "Dos 5 Premiers Crus da classificação de 1855, três ficam em Pauillac.",
      "O cascalho profundo (graves) drena a água e devolve calor às videiras à noite — ideal para o Cabernet amadurecer.",
      "A D2, a 'Route des Châteaux', é uma das estradas de vinho mais famosas do planeta.",
    ],
    toDo: [
      "Percorrer a D2 entre os châteaux",
      "Visita e degustação em um Grand Cru Classé",
      "Passeio à beira do Gironde",
    ],
    photoSpots: ["Portões do Château Pichon", "Vinhedos ao pôr do sol na D2"],
    bestTimes: "Tarde para as degustações; luz rasante da tarde sobre os vinhedos.",
    localWines: ["Pauillac AOC"],
    coords: { lat: 45.1985, lng: -0.7461 },
    visitedOnDays: [2],
  },
  {
    slug: "cussac-fort-medoc",
    name: "Cussac-Fort-Médoc",
    region: "Médoc · Margem esquerda",
    tagline: "Vauban à beira do estuário",
    heroImage: "https://www.guide-bordeaux-gironde.com/_bibli/articlesPage/205/images/fort-medoc-3.jpg?v=preload",
    history:
      "Vila do Médoc conhecida pelo Fort Médoc, fortaleza projetada por Vauban no fim do século XVII para proteger Bordeaux junto com a Cidadela de Blaye, na outra margem. Hoje é ponto de parada tranquilo entre os grandes vinhedos, com forte tradição de ostras e frutos do mar do Atlântico próximo.",
    curiosities: [
      "O Fort Médoc faz parte da 'cintura de ferro' de Vauban, Patrimônio da UNESCO.",
      "Formava um triângulo de fogo cruzado com Blaye e a ilha de Pâté para fechar o estuário.",
    ],
    toDo: ["Fort Médoc", "Degustação de ostras à beira do Gironde"],
    photoSpots: ["Muralhas do Fort Médoc", "Estuário ao entardecer"],
    localWines: ["Haut-Médoc AOC"],
    coords: { lat: 45.1214, lng: -0.7333 },
    visitedOnDays: [2],
  },
  {
    slug: "cadillac",
    name: "Cadillac",
    region: "Entre-deux-Mers · Sauternais",
    tagline: "O château dos duques e o ouro de Sauternes",
    heroImage: "https://www.chateau-cadillac.fr/var/cmn_inter/storage/images/_aliases/header_dropdown_image_webp/2/4/2/0/120050242-1-fre-FR/daa5381ab136-Chateau-Cadillac-c-CMN-visiter.webp.webp",
    history:
      "Bastide fortificada do século XIII à margem direita da Garonne, Cadillac é dominada pelo imponente Château des Ducs d'Épernon, erguido no início do século XVII. A região produz vinhos doces botritizados na órbita de Sauternes e Barsac — os célebres 'ouro líquido'. E sim: o nome batizou a marca de automóveis, via o explorador Antoine de la Mothe, senhor de Cadillac, fundador de Detroit.",
    curiosities: [
      "Antoine de la Mothe-Cadillac fundou a cidade de Detroit — daí o nome da montadora Cadillac.",
      "O Château des Ducs d'Épernon (na própria vila) guarda lareiras monumentais e tapeçarias históricas.",
      "A excursão QIMO segue ao Château Royal de Cazeneuve, em Préchac — residência de Henri IV e da Rainha Margot, ainda habitada pela família de Sabran-Pontevès.",
      "Os vinhos doces nascem da 'podridão nobre' (Botrytis cinerea) que concentra o açúcar das uvas.",
    ],
    toDo: [
      "Tour privativo do Château Royal de Cazeneuve (de Henri IV)",
      "Brinde com Sauternes recebido pelos proprietários",
      "Château des Ducs d'Épernon e as muralhas da bastide",
    ],
    photoSpots: ["Château Royal de Cazeneuve", "Portas fortificadas da bastide de Cadillac"],
    localWines: ["Cadillac AOC (doce)", "Sauternes", "Barsac"],
    coords: { lat: 44.6353, lng: -0.3167 },
    visitedOnDays: [3],
  },
  {
    slug: "blaye",
    name: "Blaye",
    region: "Côtes de Blaye · Margem direita",
    tagline: "A cidadela de Vauban sobre o estuário",
    heroImage: "https://www.guide-bordeaux-gironde.com/_bibli/annonces/4674/hd/citadelle-de-blaye-spiritprod33-adobestock.jpg?v=preload",
    history:
      "Debruçada sobre o maior estuário da Europa, Blaye é guardada por uma cidadela monumental construída por Vauban no fim do século XVII — hoje Patrimônio Mundial da UNESCO. Suas Côtes produzem tintos redondos e acessíveis à base de Merlot. A Route de la Corniche Fleurie, à beira d'água, é uma das estradas mais pitorescas da Gironde.",
    curiosities: [
      "A Cidadela de Blaye integra a rede de fortificações de Vauban reconhecida pela UNESCO.",
      "Junto com o Fort Médoc e o Fort Pâté formava a defesa tripla do estuário.",
      "A Corniche Fleurie é pontilhada de casinhas de pescadores com carrelets (redes suspensas).",
    ],
    toDo: [
      "Cidadela de Vauban e suas muralhas",
      "Route de la Corniche Fleurie",
      "Degustação de Blaye Côtes de Bordeaux",
    ],
    photoSpots: ["Vista do estuário do alto da cidadela", "Carrelets na Corniche Fleurie"],
    localWines: ["Blaye Côtes de Bordeaux"],
    coords: { lat: 45.1281, lng: -0.6633 },
    visitedOnDays: [4],
  },
  {
    slug: "bourg-sur-gironde",
    name: "Bourg-sur-Gironde",
    region: "Côtes de Bourg · Margem direita",
    tagline: "Um balcão medieval sobre dois rios",
    heroImage: "https://www.canaldes2mersavelo.com/sites/canaldes2mers/files/styles/slider_iti/public/medias/images/bourg-village-medievale-gironde.png.webp?h=827069f2&itok=HU8Rq5Fj",
    history:
      "Cidadezinha medieval empoleirada sobre um promontório calcário, na confluência da Dordogne com a Garonne. Suas ruas em degraus, a cidade alta e a cidade baixa, e o casario de pedra clara guardam o charme de um antigo porto fluvial. As Côtes de Bourg, 'a pequena Suíça girondina', produzem tintos encorpados de Merlot e Malbec.",
    curiosities: [
      "As grutas de Pair-non-Pair, próximas, guardam gravuras rupestres de mais de 30 mil anos.",
      "O Malbec (aqui chamado Côt) tem presença histórica nas Côtes de Bourg.",
    ],
    toDo: ["Passeio pela cidade alta", "Mirante sobre a confluência dos rios", "Château de la Citadelle"],
    photoSpots: ["Panorama da confluência Dordogne/Garonne", "Escadarias medievais"],
    localWines: ["Côtes de Bourg"],
    coords: { lat: 45.0403, lng: -0.5636 },
    visitedOnDays: [4],
  },
  {
    slug: "libourne",
    name: "Libourne",
    region: "Margem direita · Dordogne",
    tagline: "A bastide-porto do vinho da margem direita",
    heroImage: "https://www.tourisme-libournais.com/uploads/Place_AbelSurchamp_5723-scaled.jpg",
    history:
      "Fundada no século XIII como bastide inglesa por Roger de Leyburn, Libourne floresceu como porto de escoamento dos vinhos de Pomerol e Saint-Émilion rumo à Inglaterra e ao norte da Europa. Sua praça central com arcadas e o mercado dos produtores mantêm viva a alma comercial da cidade, encravada entre os grandes terroirs de Merlot.",
    curiosities: [
      "O nome vem de Roger de Leyburn, senhor inglês que fundou a bastide.",
      "Era o porto por onde escoavam os vinhos de Pomerol e Saint-Émilion.",
      "O mercado acontece na Place Abel Surchamp, cercada de arcadas medievais.",
    ],
    toDo: ["Mercado dos produtores", "Place Abel Surchamp e arcadas", "Passeio de bike pela beira do rio"],
    photoSpots: ["Arcadas da praça central", "Torre do Grand Port à beira da Dordogne"],
    bestTimes: "Manhã, no auge do mercado dos produtores.",
    localWines: ["Pomerol", "Saint-Émilion", "Lalande-de-Pomerol"],
    coords: { lat: 44.9147, lng: -0.2439 },
    visitedOnDays: [5, 6],
  },
  {
    slug: "saint-emilion",
    name: "Saint-Émilion",
    region: "Margem direita · Grand Cru",
    tagline: "Uma vila medieval esculpida na rocha e no vinho",
    heroImage: "https://www.saint-emilion-tourisme.com/media/cache/ogimage/uploads/img/saint-emilion-tourisme-com-65a161889c990278662155.jpg",
    history:
      "Nascida ao redor da ermida do monge Émilion no século VIII, Saint-Émilion é uma das vilas mais bonitas da França e a primeira paisagem vitícola inscrita como Patrimônio Mundial da UNESCO. Sua igreja monolítica — escavada inteira na rocha — e as ruelas íngremes de pedra calcária guardam adegas subterrâneas onde envelhecem os grandes Merlots da margem direita.",
    curiosities: [
      "A igreja monolítica é a maior igreja escavada em rocha da Europa.",
      "Os macarons de Saint-Émilion nasceram no século XVII com as freiras ursulinas.",
      "A jurisdição de Saint-Émilion foi a primeira paisagem vitícola declarada Patrimônio da UNESCO.",
    ],
    toDo: [
      "Igreja monolítica e catacumbas",
      "Torre do Rei (Tour du Roy) — vista panorâmica",
      "Degustação de Grand Cru Classé",
      "Provar os macarons tradicionais",
    ],
    photoSpots: [
      "Vista da vila do alto da Tour du Roy",
      "Ruela Escalier de la Madeleine",
      "Vinhedos ao redor do campanário",
    ],
    bestTimes: "Manhã cedo, antes dos excursionistas; luz dourada no fim da tarde sobre os telhados.",
    restaurants: ["Logis de la Cadène (1 estrela Michelin)", "L'Envers du Décor"],
    localWines: ["Saint-Émilion Grand Cru", "Saint-Émilion AOC"],
    coords: { lat: 44.8938, lng: -0.1556 },
    visitedOnDays: [5],
  },
];
