import type { ConciergeContact, FrenchPhrase } from "@/lib/types";

// Contatos — os valores QIMO devem ser confirmados/atualizados no painel admin.
export const conciergeContacts: ConciergeContact[] = [
  {
    slug: "qimo-whatsapp",
    label: "Suporte QIMO (WhatsApp)",
    type: "whatsapp",
    value: "5521995453817",
    hint: "Equipe QIMO à disposição 24h durante a viagem",
    icon: "MessageCircle",
  },
  {
    slug: "qimo-call",
    label: "Ligar para a QIMO",
    type: "call",
    value: "+5521995453817",
    hint: "Concierge de viagem",
    icon: "Phone",
  },
  {
    slug: "emergency-eu",
    label: "Emergência (Europa)",
    type: "emergency",
    value: "112",
    hint: "Número único europeu — polícia, bombeiros e ambulância",
    icon: "Siren",
  },
  {
    slug: "samu",
    label: "SAMU (ambulância França)",
    type: "emergency",
    value: "15",
    hint: "Urgência médica na França",
    icon: "Ambulance",
  },
  {
    slug: "police",
    label: "Polícia (França)",
    type: "emergency",
    value: "17",
    hint: "Police / Gendarmerie",
    icon: "Shield",
  },
  {
    slug: "consulado-br-bordeaux",
    label: "Consulado Honorário do Brasil (Bordeaux)",
    type: "call",
    value: "+33556811200",
    hint: "8 place des Quinconces · atendimento por marcação (serviços limitados)",
    icon: "Landmark",
  },
  {
    slug: "consulado-br-paris",
    label: "Consulado-Geral do Brasil (Paris)",
    type: "call",
    value: "+33145616300",
    hint: "Assistência consular plena a brasileiros na França",
    icon: "Landmark",
  },
  {
    slug: "taxi-bordeaux",
    label: "Táxi de Bordeaux",
    type: "call",
    value: "+33556967034",
    hint: "Taxi Télé (rádio-táxi de Bordeaux)",
    icon: "Car",
  },
  {
    slug: "hospital-bordeaux",
    label: "Hospital — CHU de Bordeaux",
    type: "maps",
    value: "CHU de Bordeaux, Place Amélie Raba-Léon",
    hint: "Principal hospital universitário da cidade",
    icon: "Cross",
  },
  {
    slug: "cambio",
    label: "Conversor de câmbio",
    type: "info",
    value: "EUR",
    hint: "Toque para converter Real ↔ Euro",
    icon: "Coins",
  },
  {
    slug: "tradutor",
    label: "Tradutor (Google)",
    type: "link",
    value: "https://translate.google.com/?sl=pt&tl=fr",
    hint: "Português ↔ Francês",
    icon: "Languages",
  },
];

export const frenchPhrases: FrenchPhrase[] = [
  { pt: "Bom dia", fr: "Bonjour", hint: "bon-jur" },
  { pt: "Boa noite", fr: "Bonsoir", hint: "bon-suár" },
  { pt: "Por favor", fr: "S'il vous plaît", hint: "sil vu plé" },
  { pt: "Obrigado(a)", fr: "Merci", hint: "mer-ci" },
  { pt: "De nada", fr: "Je vous en prie", hint: "je vuz-an pri" },
  { pt: "Com licença / Desculpe", fr: "Excusez-moi", hint: "eks-kü-zé muá" },
  { pt: "Você fala inglês?", fr: "Parlez-vous anglais ?", hint: "par-lé vu an-glê" },
  { pt: "A conta, por favor", fr: "L'addition, s'il vous plaît", hint: "la-di-si-on sil vu plé" },
  { pt: "Uma taça de vinho tinto", fr: "Un verre de vin rouge", hint: "an vér de van ruj" },
  { pt: "Saúde! (brinde)", fr: "Santé !", hint: "san-té" },
  { pt: "Está delicioso", fr: "C'est délicieux", hint: "sé dé-li-si-ê" },
  { pt: "Quanto custa?", fr: "Combien ça coûte ?", hint: "com-biã sa cut" },
  { pt: "Onde fica o banheiro?", fr: "Où sont les toilettes ?", hint: "u son lê tualét" },
  { pt: "Preciso de ajuda", fr: "J'ai besoin d'aide", hint: "jé be-zuã déd" },
];

export const etiquette = [
  "Cumprimente sempre com 'Bonjour' ao entrar em lojas e restaurantes — é sinal de educação essencial.",
  "O almoço costuma ser servido entre 12h e 14h; o jantar a partir das 19h30–20h.",
  "A gorjeta (service) já está incluída na conta; arredondar é gentileza, não obrigação.",
  "Vinho é levado a sério — pergunte a recomendação do sommelier, ele terá prazer em ajudar.",
  "Fale baixo em restaurantes e espaços públicos; discrição é valorizada.",
  "Ao brindar, olhe nos olhos e diga 'Santé' — dizem que dá azar não olhar.",
];
