import type { Experience } from "@/lib/types";

export const experiences: Experience[] = [
  {
    slug: "degustacao-privada-medoc",
    heroImage: "/photos/wine-glass.jpg",
    name: "Degustação privada nos Grands Crus do Médoc",
    description:
      "Percurso pela lendária D2 e degustação reservada em um 5º Grand Cru Classé de Pauillac (Grand-Puy-Ducasse ou Pédesclaux).",
    duration: "≈ 3h15",
    location: "Pauillac",
    category: "Enoturismo",
    qimoSelect: true,
    relatedDay: 2,
  },
  {
    slug: "ostras-medoc",
    heroImage: "/photos/food-ostras.jpg",
    name: "Degustação de ostras frescas do Médoc",
    description: "Ostras do Atlântico servidas com um branco seco à beira do estuário do Gironde.",
    duration: "≈ 1h",
    location: "Cussac-Fort-Médoc",
    category: "Gastronomia",
    qimoSelect: true,
    relatedDay: 2,
  },
  {
    slug: "bike-medoc",
    heroImage: "/photos/hero-medoc.jpg",
    name: "Bike pelos vinhedos do Médoc",
    description: "Passeio guiado de bicicleta entre parcelas de Cabernet Sauvignon.",
    duration: "≈ 3h",
    location: "Pauillac",
    category: "Ativo",
    relatedDay: 2,
  },
  {
    slug: "chateau-real-sauternes",
    heroImage: "/photos/wine-sauternes.jpg",
    name: "Tour privativo de château real com brinde de Sauternes",
    description: "Château des Ducs d'Épernon e um brinde com o ouro líquido de Sauternes.",
    duration: "≈ 3h30",
    location: "Cadillac",
    category: "História & Vinho",
    qimoSelect: true,
    relatedDay: 3,
  },
  {
    slug: "remy-martin",
    heroImage: "/photos/cellar-barrels.jpg",
    name: "Rendez-Vous Chez Rémy Martin",
    description: "Visita exclusiva à casa de Cognac Rémy Martin com degustação de conhaques raros.",
    duration: "≈ 4h30",
    location: "Cognac",
    category: "Masterpiece Collection",
    qimoSelect: true,
    relatedDay: 4,
  },
  {
    slug: "wine-art-blaye",
    heroImage: "/photos/city-blaye.jpg",
    name: "Experiência íntima com conhecedores de vinho e arte",
    description: "Encontro reservado com produtores e artistas da Côte de Blaye.",
    duration: "≈ 2h30",
    location: "Blaye",
    category: "Cultura & Vinho",
    qimoSelect: true,
    relatedDay: 4,
  },
  {
    slug: "cooking-class-saint-emilion",
    heroImage: "/photos/food-magret.jpg",
    name: "Aula de culinária em château",
    description: "Cozinhar ao lado de um chef em um château Grand Cru, com almoço harmonizado.",
    duration: "≈ 4h",
    location: "Saint-Émilion",
    category: "Masterpiece Collection",
    qimoSelect: true,
    relatedDay: 5,
  },
  {
    slug: "picnic-grand-cru",
    heroImage: "/photos/exp-picnic.jpg",
    name: "Piquenique Grand Cru entre as vinhas",
    description: "Piquenique gastronômico nas vinhas de um Grand Cru Classé de Saint-Émilion.",
    duration: "≈ 3h",
    location: "Saint-Émilion",
    category: "Masterpiece Collection",
    qimoSelect: true,
    relatedDay: 5,
  },
  {
    slug: "bassins-lumieres",
    heroImage: "/photos/exp-bassins.jpg",
    name: "After Hours no Bassins des Lumières",
    description:
      "Visita noturna exclusiva ao maior centro de arte digital do mundo, numa antiga base de submarinos.",
    duration: "≈ 2h30",
    location: "Bordeaux",
    category: "Arte & Cultura",
    qimoSelect: true,
    relatedDay: 6,
  },
  {
    slug: "sidecar-bordeaux",
    heroImage: "/photos/exp-sidecar.jpg",
    name: "Tour de sidecar retrô por Bordeaux",
    description: "A cidade — de dia ou à noite — a bordo de um sidecar clássico dos anos 1950.",
    duration: "≈ 1h",
    location: "Bordeaux",
    category: "Masterpiece Collection",
    qimoSelect: true,
    relatedDay: 7,
  },
];
