import type { Day } from "@/lib/types";

// Roteiro real — QIMO Bordeaux Experience
// Cruzeiro fluvial SS Bon Voyage · 25/10 → 01/11/2026
// Fonte: BV261025 - Qimo - Program Overview.xlsx

export const TRIP = {
  brand: "QIMO",
  title: "Bordeaux Experience",
  subtitle: "Um cruzeiro pelos rios da grande Bordeaux",
  ship: "SS Bon Voyage",
  startDate: "2026-10-25",
  endDate: "2026-11-01",
  boardingISO: "2026-10-25T15:00:00",
  nights: 7,
};

export const itinerary: Day[] = [
  {
    n: 1,
    date: "2026-10-25",
    title: "Embarque em Bordeaux",
    subtitle: "Bem-vindo a bordo",
    ports: ["Bordeaux"],
    overnight: "Bordeaux",
    dressCode: "Casual elegante",
    ship: [{ city: "Bordeaux", eta: null, etd: "overnight" }],
    note: "Chegada, transfer privativo do aeroporto e primeira noite atracado no coração de Bordeaux.",
    activities: [
      {
        id: "d1-transfer",
        time: null,
        title: "Transfer do aeroporto (BOD) para o navio",
        type: "transfer",
        location: "Aeroporto de Bordeaux-Mérignac",
        description:
          "Recepção QIMO no desembarque e transfer privativo até o cais. Acomodação nas suítes, coquetel de boas-vindas e jantar inaugural a bordo.",
      },
    ],
  },
  {
    n: 2,
    date: "2026-10-26",
    title: "Médoc & Pauillac",
    subtitle: "Ostras, Grands Crus e cancan",
    ports: ["Bordeaux", "Cussac-Fort-Médoc", "Pauillac"],
    overnight: "Pauillac",
    dressCode: "Casual elegante · sapato confortável para os vinhedos",
    ship: [
      { city: "Bordeaux", eta: null, etd: "08:00" },
      { city: "Cussac-Fort-Médoc", eta: "11:00", etd: "12:00" },
      { city: "Pauillac La Fayette", eta: "13:00", etd: "17:30" },
    ],
    activities: [
      {
        id: "d2-lecture",
        time: "10:00–11:00",
        title: "Palestra: Como Bordeaux sobreviveu à Segunda Guerra",
        type: "lecture",
        capacity: 124,
        description:
          "A bordo, durante a navegação, um mergulho na história de Bordeaux sob a ocupação — e como o vinho atravessou o período.",
      },
      {
        id: "d2-oysters",
        time: "11:00–12:00",
        title: "Degustação de ostras frescas do Médoc",
        type: "tasting",
        location: "Cussac-Fort-Médoc",
        capacity: 124,
        qimoSelect: true,
        description:
          "Ostras colhidas na costa atlântica, servidas com um branco seco do Médoc à beira do Gironde.",
      },
      {
        id: "d2-grandpuy",
        time: "14:00–17:15",
        title: "Rota dos Châteaux do Médoc — degustação privada no Château Grand-Puy-Ducasse",
        type: "winery",
        location: "Pauillac",
        capacity: 90,
        qimoSelect: true,
        linkedWinery: "grand-puy-ducasse",
        dressCode: "Casual elegante",
        description:
          "Percurso pela mítica D2 entre os Grands Crus Classés, com degustação privada em um 5º Cru Classé de Pauillac.",
      },
      {
        id: "d2-pedesclaux",
        time: "14:00–17:15",
        title: "Rota dos Châteaux do Médoc — degustação privada no Château Pédesclaux",
        type: "winery",
        location: "Pauillac",
        capacity: 45,
        linkedWinery: "pedesclaux",
        dressCode: "Casual elegante",
        description:
          "Alternativa íntima: um 5º Cru Classé restaurado com arquitetura contemporânea e vista sobre os vinhedos.",
      },
      {
        id: "d2-bike",
        time: "14:00–17:00",
        title: "Let's Go: bike pelos vinhedos do Médoc",
        type: "active",
        location: "Pauillac",
        capacity: 24,
        description:
          "Passeio guiado de bicicleta entre as parcelas de Cabernet Sauvignon, com paradas para fotos e degustação.",
      },
      {
        id: "d2-cancan",
        time: "17:00–18:00",
        title: "Entretenimento: demonstração de French Cancan",
        type: "entertainment",
        capacity: 124,
        description: "A bordo, ao entardecer — um espetáculo à moda da Belle Époque parisiense.",
      },
    ],
  },
  {
    n: 3,
    date: "2026-10-27",
    title: "Cadillac & Sauternes",
    subtitle: "Château real e ouro líquido",
    ports: ["Cadillac", "Blaye"],
    overnight: "Blaye",
    dressCode: "Casual elegante",
    ship: [
      { city: "Cadillac", eta: "08:00", etd: "14:30" },
      { city: "Blaye", eta: "19:00", etd: "overnight" },
    ],
    activities: [
      {
        id: "d3-royal",
        time: "09:30–13:00",
        title: "Tour privativo do Château Royal de Cazeneuve com brinde de Sauternes",
        type: "experience",
        location: "Préchac (excursão a partir de Cadillac)",
        capacity: 124,
        qimoSelect: true,
        linkedCity: "cadillac",
        description:
          "Visita íntima ao Château Royal de Cazeneuve — residência de Henri IV e da Rainha Margot, ainda pertencente à família de Sabran-Pontevès — recebida pelos próprios proprietários, seguida de um brinde com o lendário Sauternes.",
      },
      {
        id: "d3-lautrec",
        time: "09:30–13:00",
        title: "A vida colorida de Toulouse-Lautrec",
        type: "experience",
        location: "Cadillac",
        capacity: 35,
        description:
          "Uma imersão na obra e na boemia do pintor que eternizou a Belle Époque francesa.",
      },
      {
        id: "d3-dupouy",
        time: "20:30–21:30",
        title: "Entretenimento: Jeremy Dupouy",
        type: "entertainment",
        capacity: 124,
        description: "Música ao vivo a bordo, já navegando rumo a Blaye.",
      },
    ],
  },
  {
    n: 4,
    date: "2026-10-28",
    title: "Blaye & Bourg",
    subtitle: "Fortaleza de Vauban e conhaque",
    ports: ["Blaye", "Bourg-sur-Gironde"],
    overnight: "Bourg-sur-Gironde",
    dressCode: "Casual elegante · agasalho para a fortaleza",
    ship: [
      { city: "Blaye", eta: "overnight", etd: "13:00" },
      { city: "Bourg sur Gironde", eta: "14:30", etd: "17:30" },
    ],
    activities: [
      {
        id: "d4-connoisseurs",
        time: "09:00–11:30",
        title: "Experiência íntima com conhecedores locais de vinho e arte",
        type: "experience",
        location: "Blaye",
        capacity: 25,
        qimoSelect: true,
        description: "Encontro reservado com produtores e artistas da região da Côte de Blaye.",
      },
      {
        id: "d4-corniche",
        time: "09:00–12:00",
        title: "Panoramas da Route de la Corniche Fleurie e Fortaleza de Blaye",
        type: "walk",
        location: "Blaye",
        capacity: 124,
        linkedCity: "blaye",
        description:
          "A cidadela de Vauban, Patrimônio Mundial da UNESCO, e a estrada florida à beira do estuário.",
      },
      {
        id: "d4-remy",
        time: "13:00–17:30",
        title: "Masterpiece Collection: Rendez-Vous Chez Rémy Martin",
        type: "experience",
        location: "Cognac",
        capacity: 35,
        qimoSelect: true,
        description:
          "Visita exclusiva à casa Rémy Martin, na região de Cognac — degustação de conhaques raros.",
      },
      {
        id: "d4-bourg",
        time: "15:00–16:00",
        title: "Passeio por Bourg-sur-Gironde",
        type: "walk",
        location: "Bourg-sur-Gironde",
        capacity: 124,
        linkedCity: "bourg-sur-gironde",
        description: "Vilarejo medieval debruçado sobre a confluência da Dordogne e da Garonne.",
      },
    ],
  },
  {
    n: 5,
    date: "2026-10-29",
    title: "Saint-Émilion",
    subtitle: "A joia da margem direita",
    ports: ["Libourne", "Saint-Émilion"],
    overnight: "Libourne",
    dressCode: "Casual elegante · sapato confortável (ruas de paralelepípedo)",
    ship: [{ city: "Libourne", eta: null, etd: "overnight" }],
    activities: [
      {
        id: "d5-walk",
        time: "09:00–14:00",
        title: "Tour a pé por Saint-Émilion com degustação",
        type: "walk",
        location: "Saint-Émilion",
        capacity: 124,
        qimoSelect: true,
        linkedCity: "saint-emilion",
        description:
          "A vila medieval Patrimônio da UNESCO, a igreja monolítica e uma degustação de Grand Cru.",
      },
      {
        id: "d5-cooking",
        time: "11:00–15:00",
        title: "Masterpiece Collection: aula de culinária em château",
        type: "experience",
        location: "Saint-Émilion",
        capacity: 17,
        qimoSelect: true,
        description: "Cozinhar ao lado de um chef em um château Grand Cru, seguido de almoço harmonizado.",
      },
      {
        id: "d5-picnic",
        time: "11:00–14:00",
        title: "Masterpiece Collection: piquenique Grand Cru no château",
        type: "meal",
        location: "Saint-Émilion",
        capacity: 30,
        qimoSelect: true,
        description: "Piquenique gastronômico entre as vinhas de um Grand Cru Classé.",
      },
      {
        id: "d5-grandcru",
        time: "11:00–13:00",
        title: "Masterpiece Collection: degustação de Grand Cru",
        type: "tasting",
        location: "Saint-Émilion",
        capacity: 14,
        qimoSelect: true,
        description: "Degustação reservada dos grandes Merlots da margem direita.",
      },
      {
        id: "d5-shuttle",
        time: "14:30–15:30",
        title: "Shuttle: Saint-Émilion",
        type: "transfer",
        location: "Saint-Émilion",
        capacity: 124,
        description: "Traslado livre entre o navio e a vila para exploração por conta própria.",
      },
      {
        id: "d5-kania",
        time: "21:00–22:00",
        title: "Entretenimento: Kania Allard",
        type: "entertainment",
        capacity: 124,
        description: "Apresentação ao vivo a bordo.",
      },
    ],
  },
  {
    n: 6,
    date: "2026-10-30",
    title: "Libourne & retorno a Bordeaux",
    subtitle: "Mercado, château e Bassins des Lumières",
    ports: ["Libourne", "Bordeaux"],
    overnight: "Bordeaux",
    dressCode: "Casual elegante",
    ship: [
      { city: "Libourne", eta: null, etd: "13:00" },
      { city: "Bordeaux", eta: "18:30", etd: "overnight" },
    ],
    activities: [
      {
        id: "d6-bike",
        time: "08:30–11:30",
        title: "Libourne e o mercado dos produtores (de bicicleta)",
        type: "active",
        location: "Libourne",
        capacity: 25,
        description: "Pedalada até o mercado matinal, entre bancas de queijos, flores e produtos da terra.",
      },
      {
        id: "d6-boutinet",
        time: "09:00–12:30",
        title: "Libourne e o mercado (Château Boutinet)",
        type: "experience",
        location: "Libourne",
        capacity: 45,
        description: "Mercado dos produtores seguido de visita a um château da região.",
      },
      {
        id: "d6-walk",
        time: "09:00–12:30",
        title: "Tour a pé por Libourne com o mercado dos produtores",
        type: "walk",
        location: "Libourne",
        capacity: 124,
        linkedCity: "libourne",
        description: "A bastide medieval e seu vibrante mercado à beira do rio.",
      },
      {
        id: "d6-paint",
        time: "15:00–17:30",
        title: "Palestra: workshop Paint & Wine",
        type: "lecture",
        capacity: 124,
        description: "Pincel em uma mão, taça na outra — uma tarde criativa a bordo.",
      },
      {
        id: "d6-lumieres",
        time: "20:00–22:30",
        title: "Nights Out: After Hours no Bassins des Lumières",
        type: "experience",
        location: "Bordeaux",
        capacity: 124,
        qimoSelect: true,
        description:
          "Visita noturna exclusiva ao maior centro de arte digital do mundo, em uma antiga base de submarinos.",
      },
    ],
  },
  {
    n: 7,
    date: "2026-10-31",
    title: "Bordeaux",
    subtitle: "A cidade, à moda dos bordaleses",
    ports: ["Bordeaux"],
    overnight: "Bordeaux",
    dressCode: "Casual elegante",
    ship: [{ city: "Bordeaux", eta: null, etd: "overnight" }],
    activities: [
      {
        id: "d7-walk",
        time: "09:00–12:00",
        title: "Do as the Locals Do: tour a pé por Bordeaux",
        type: "walk",
        location: "Bordeaux",
        capacity: 124,
        qimoSelect: true,
        linkedCity: "bordeaux",
        description:
          "A Place de la Bourse, o Miroir d'Eau, a Grosse Cloche e os segredos do centro histórico Patrimônio da UNESCO.",
      },
      {
        id: "d7-bike",
        time: "09:30–12:00",
        title: "Let's Go: bike pelas ruelas de Bordeaux",
        type: "active",
        location: "Bordeaux",
        capacity: 25,
        description: "As vielas escondidas, os cais reabilitados e os bairros criativos sobre duas rodas.",
      },
      {
        id: "d7-sidecar1",
        time: "15:00–16:00",
        title: "Masterpiece Collection: tour de sidecar retrô por Bordeaux",
        type: "experience",
        location: "Bordeaux",
        capacity: 7,
        qimoSelect: true,
        description: "A cidade a bordo de um sidecar clássico dos anos 1950 — glamour puro.",
      },
      {
        id: "d7-sidecar2",
        time: "21:00–22:30",
        title: "Masterpiece Collection: tour romântico de sidecar retrô",
        type: "experience",
        location: "Bordeaux",
        capacity: 4,
        qimoSelect: true,
        description: "Bordeaux iluminada à noite, em um passeio íntimo de sidecar.",
      },
    ],
  },
  {
    n: 8,
    date: "2026-11-01",
    title: "Desembarque",
    subtitle: "Au revoir, Bordeaux",
    ports: ["Bordeaux"],
    dressCode: "Casual",
    ship: [{ city: "Bordeaux", eta: null, etd: null }],
    note: "Café da manhã a bordo e transfer privativo até o aeroporto.",
    activities: [
      {
        id: "d8-transfer",
        time: null,
        title: "Transfer do navio para o aeroporto (BOD)",
        type: "transfer",
        location: "Bordeaux",
        description: "Desembarque após o café da manhã e transfer privativo QIMO ao aeroporto.",
      },
    ],
  },
];
