import type { Restaurant } from "@/lib/types";

const NAO_DIVULGADO = "Informação não divulgada oficialmente.";

function score(
  gastronomy: number,
  wine: number,
  ambience: number,
  service: number,
  location: number,
  exclusivity: number,
  value: number,
  bookingEase: number,
  overall: number
): NonNullable<Restaurant["qimoScores"]> {
  return { gastronomy, wine, ambience, service, location, exclusivity, value, bookingEase, overall };
}

// Curadoria QIMO validada em 11/07/2026 com fontes oficiais e Michelin quando disponível.
// Fotos locais são placeholders editoriais do guia; substituir no CMS por fotos oficiais autorizadas.
export const restaurants: Restaurant[] = [
  {
    slug: "le-pressoir-dargent",
    name: "Le Pressoir d'Argent Gordon Ramsay",
    city: "Bordeaux",
    neighborhood: "Grand Théâtre",
    category: "michelin",
    heroImage: "https://bordeaux.intercontinental.com/wp-content/uploads/sites/4/2022/10/InterContinental-Bordeaux-Gordon-Ramsay-Pressoir-Argent-Salle.jpg",
    gallery: [
      "https://bordeaux.intercontinental.com/wp-content/uploads/sites/4/2022/10/InterContinental-Bordeaux-Gordon-Ramsay-Pressoir-Argent-Salle.jpg",
    ],
    description:
      "No primeiro andar do InterContinental Bordeaux, o Le Pressoir d'Argent é uma das mesas mais cerimoniais da cidade. A experiência combina serviço de hotelaria de luxo, sala elegante e uma cozinha de alta precisão ligada ao repertório de Gordon Ramsay. O ritual da prensa de lagosta em prata maciça segue como assinatura da casa, ao lado de produtos nobres do Atlântico, trufas, foie gras e uma adega ampla para explorar Bordeaux em profundidade. É uma escolha natural para um jantar especial, com ritmo de menu degustação e ambiente mais formal.",
    chef: "Gordon Ramsay; chef executivo local não divulgado oficialmente.",
    specialty: "Alta gastronomia francesa, frutos do mar e produtos regionais",
    stars: "2 estrelas Michelin",
    michelin: "2 estrelas Michelin",
    averageTicket: "Menus oficiais a partir de €195",
    priceBand: "Acima de €100",
    bestFor: "Jantar de celebração",
    duration: "2h30 a 3h30",
    dressCode: "Elegante",
    reservationRequired: true,
    reservationAdvice: "Reservar com antecedência, especialmente para sexta e sábado.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://bordeaux.intercontinental.com/le-pressoir-dargent-gordon-ramsay/",
    bookingUrl: "https://module.lafourchette.com/fr_FR/module/7537-57112",
    bookingChannel: "Reserva oficial",
    phone: "+33557304444",
    address: "2-5 place de la Comédie, 33000 Bordeaux",
    coords: { lat: 44.84239, lng: -0.57487 },
    highlights: ["Experiência Michelin", "Carta de vinhos extensa", "Ambiente formal"],
    seals: ["Escolha QIMO", "Michelin", "Reserva concorrida"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva online oficial disponível.",
    },
    qimoScores: score(9.6, 9.7, 9.4, 9.3, 9.8, 9.7, 7.8, 8.8, 9.4),
    sommelierTip:
      "Peça orientação para comparar um grande branco de Pessac-Léognan com tintos maduros da margem esquerda. Para frutos do mar e molhos delicados, brancos de Graves e Pessac-Léognan costumam dialogar melhor que tintos potentes.",
    qimoNote: "A mesa mais luxuosa para quem quer alta gastronomia clássica no centro de Bordeaux.",
    sourcePrimary: "https://bordeaux.intercontinental.com/le-pressoir-dargent-gordon-ramsay/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    featured: true,
    sortOrder: 1,
  },
  {
    slug: "maison-nouvelle",
    name: "Maison Nouvelle",
    city: "Bordeaux",
    neighborhood: "Chartrons",
    category: "michelin",
    heroImage: "https://maison-nouvelle.fr/wp-content/uploads/2025/03/lieu-3.jpg",
    gallery: ["https://maison-nouvelle.fr/wp-content/uploads/2025/03/lieu-3.jpg"],
    description:
      "A Maison Nouvelle marca a fase mais autoral de Philippe Etchebest em Bordeaux. Instalada nos Chartrons, a casa trabalha menus gastronômicos de alta precisão, com linguagem contemporânea e serviço cuidado sem perder a energia bordalesa do bairro. Para o viajante brasileiro que acompanha chefs franceses, é também uma mesa de referência pela personalidade do chef e pela evolução recente no Guia Michelin. A experiência pede tempo, reserva antecipada e atenção ao vinho: o formato de menu degustação favorece harmonizações elegantes, sobretudo com rótulos de Bordeaux menos óbvios.",
    chef: "Philippe Etchebest",
    specialty: "Cozinha gastronômica contemporânea",
    stars: "2 estrelas Michelin",
    michelin: "2 estrelas Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Menu degustação autoral",
    duration: "2h30 a 3h",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reservar com bastante antecedência.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.maison-nouvelle.fr/",
    bookingUrl: "https://www.maison-nouvelle.fr/",
    bookingChannel: "Site oficial",
    address: "11 rue Rode, 33000 Bordeaux",
    coords: { lat: 44.85207, lng: -0.57004 },
    highlights: ["Menu degustação", "Chef renomado", "Experiência Michelin"],
    seals: ["Escolha QIMO", "Michelin", "Reserva concorrida"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(9.5, 9.2, 9.1, 9.1, 8.8, 9.5, 7.7, 8.4, 9.2),
    sommelierTip:
      "A cozinha contemporânea permite alternar brancos de Pessac-Léognan, tintos de Saint-Émilion com taninos polidos e, no final, Sauternes em pequenas doses para notas doces ou foie gras.",
    sourcePrimary: "https://www.maison-nouvelle.fr/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    featured: true,
    sortOrder: 2,
  },
  {
    slug: "lobservatoire-du-gabriel",
    name: "L'Observatoire du Gabriel",
    city: "Bordeaux",
    neighborhood: "Place de la Bourse",
    category: "michelin",
    heroImage: "https://www.teritoria.com/wp-content/uploads/2023/11/3115b.jpg",
    description:
      "No edifício histórico do Gabriel, de frente para a Place de la Bourse, L'Observatoire ocupa o registro mais gastronômico da casa. É uma experiência de Bordeaux em chave monumental: vista urbana, serviço de grande ocasião e cozinha moderna com ambição de destino. Para quem busca uma noite memorável sem sair do coração da cidade, a localização é imbatível. A visita funciona melhor no jantar, quando a praça e o Miroir d'Eau criam um cenário raro para chegar ou sair a pé.",
    chef: "Bertrand Noeureuil",
    specialty: "Cozinha moderna francesa",
    stars: "2 estrelas Michelin",
    michelin: "2 estrelas Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Jantar panorâmico no centro histórico",
    duration: "2h30 a 3h",
    dressCode: "Elegante",
    reservationRequired: true,
    reservationAdvice: "Reservar com antecedência; mesas com vista são concorridas.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://bordeaux-gabriel.fr/",
    bookingUrl: "https://bordeaux-gabriel.fr/",
    bookingChannel: "Site oficial",
    address: "10 place de la Bourse, 33000 Bordeaux",
    coords: { lat: 44.84131, lng: -0.56959 },
    highlights: ["Vista histórica", "Experiência Michelin", "Jantar especial"],
    seals: ["Michelin", "Experiência romântica", "Escolha QIMO"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(9.4, 9.3, 9.6, 9.2, 10, 9.5, 7.6, 8.3, 9.3),
    sommelierTip:
      "A localização pede Bordeaux clássico: Margaux para elegância, Saint-Julien para estrutura e brancos de Graves para entradas marinhas. Converse sobre safras prontas para consumo, não apenas rótulos famosos.",
    sourcePrimary: "https://bordeaux-gabriel.fr/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    featured: true,
    sortOrder: 3,
  },
  {
    slug: "le-pavillon-des-boulevards",
    name: "Le Pavillon des Boulevards",
    city: "Bordeaux",
    neighborhood: "Barrière du Médoc",
    category: "michelin",
    heroImage: "https://lepavillondesboulevards.fr/wp-content/uploads/2025/01/IMG_0880-scaled.jpg",
    description:
      "Um endereço discreto e refinado fora do eixo mais turístico, o Le Pavillon des Boulevards oferece uma Bordeaux gastronômica mais residencial. A casa é indicada para quem prefere serviço clássico, cozinha precisa e uma atmosfera menos cenográfica que os restaurantes de hotel. É uma boa escolha para almoço ou jantar de alta gastronomia quando a ideia é conversar com calma e deixar o vinho conduzir parte da experiência. A presença Michelin reforça o nível técnico, mas a sensação é de casa madura, estável e elegante.",
    chef: "Thomas Morel",
    specialty: "Cozinha moderna francesa",
    stars: "1 estrela Michelin",
    michelin: "1 estrela Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Almoço gastronômico tranquilo",
    duration: "2h a 3h",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reservar com antecedência.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.restaurant-lepavillondesboulevards.fr/",
    bookingUrl: "https://www.restaurant-lepavillondesboulevards.fr/",
    bookingChannel: "Site oficial",
    address: "120 rue Croix-de-Seguey, 33000 Bordeaux",
    coords: { lat: 44.85183, lng: -0.59182 },
    highlights: ["Mesa Michelin", "Ambiente discreto", "Boa carta de vinhos"],
    seals: ["Michelin", "Experiência romântica"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(9.1, 9, 8.8, 9, 8.4, 8.9, 7.9, 8.2, 8.9),
    sommelierTip:
      "Boa casa para pedir tintos de margem esquerda com alguma evolução em garrafa. Se a refeição tiver peixe ou legumes, abra espaço para um branco seco de Pessac-Léognan.",
    sourcePrimary: "https://www.restaurant-lepavillondesboulevards.fr/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    sortOrder: 4,
  },
  {
    slug: "loiseau-bleu",
    name: "L'Oiseau Bleu",
    city: "Bordeaux",
    neighborhood: "Saint-Seurin",
    category: "michelin",
    heroImage: "https://ugc.zenchef.com/3/4/1/9/0/0/1/5/1/9/1/0/4/1759163915_442/ec20a959b911db1d3d1467d88e997804.website.jpg",
    description:
      "L'Oiseau Bleu é uma das mesas contemporâneas mais consistentes de Bordeaux para quem deseja Michelin sem o peso de uma sala excessivamente formal. A cozinha trabalha técnica, produto e apresentação com bom senso, em um ambiente elegante e urbano. É uma opção interessante para casais ou pequenos grupos que querem jantar muito bem e ainda manter uma noite leve. A carta permite explorar Bordeaux com menos ostentação e mais curiosidade, especialmente em denominações que ficam fora do circuito dos rótulos mais célebres.",
    chef: "Informação não divulgada oficialmente.",
    specialty: "Cozinha moderna",
    stars: "1 estrela Michelin",
    michelin: "1 estrela Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Jantar sofisticado e contemporâneo",
    duration: "2h a 3h",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reservar com antecedência.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.loiseaubleu.fr/",
    bookingUrl: "https://www.loiseaubleu.fr/",
    bookingChannel: "Site oficial",
    address: "127 avenue Thiers, 33100 Bordeaux",
    coords: { lat: 44.8423, lng: -0.5522 },
    highlights: ["Mesa Michelin", "Cozinha contemporânea", "Bom para jantar"],
    seals: ["Michelin", "Experiência romântica"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(8.9, 8.8, 8.7, 8.7, 8.2, 8.7, 8, 8.1, 8.7),
    sommelierTip:
      "Aposte em Bordeaux de textura média: Saint-Émilion para pratos mais terrosos, Pessac-Léognan branco para peixes e legumes, e Fronsac para uma descoberta menos óbvia.",
    sourcePrimary: "https://www.loiseaubleu.fr/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 5,
  },
  {
    slug: "ressources",
    name: "Ressources",
    city: "Bordeaux",
    neighborhood: "Saint-Seurin",
    category: "michelin",
    heroImage: "https://prod-pics.guide.michelin.com/api/public/content/e9f13b9cfd2344a0853303d0fb2234a6.jpg?format=webp",
    description:
      "Ressources representa uma Bordeaux gastronômica mais íntima e contemporânea, com cozinha focada em produto, precisão e sensibilidade de estação. É uma mesa para quem gosta de restaurantes menores, com narrativa culinária clara e menos aparato de luxo. A experiência conversa bem com viajantes que já fizeram grandes clássicos e procuram algo atual, autoral e muito bordalês. Por ter escala mais contida, a reserva deve ser tratada com atenção; a recompensa é uma refeição de ritmo elegante e leitura moderna dos produtos do Sudoeste.",
    chef: "Tanguy Laviale",
    specialty: "Cozinha moderna de produto",
    stars: "1 estrela Michelin",
    michelin: "1 estrela Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Gastronomia contemporânea intimista",
    duration: "2h a 3h",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reservar com antecedência.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.ressources-restaurant.com/",
    bookingUrl: "https://www.ressources-restaurant.com/",
    bookingChannel: "Site oficial",
    address: "126 rue Fondaudège, 33000 Bordeaux",
    coords: { lat: 44.84849, lng: -0.58362 },
    highlights: ["Mesa Michelin", "Cozinha autoral", "Ambiente intimista"],
    seals: ["Michelin", "Escolha QIMO"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(9, 8.8, 8.5, 8.8, 8.6, 8.8, 8.1, 8, 8.8),
    sommelierTip:
      "Peça vinhos com energia e frescor: brancos secos de Graves, tintos de Castillon ou Francs Côtes de Bordeaux e garrafas com menos madeira para acompanhar a cozinha de produto.",
    sourcePrimary: "https://www.ressources-restaurant.com/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    sortOrder: 6,
  },
  {
    slug: "cent33",
    name: "Cent33",
    city: "Bordeaux",
    neighborhood: "Chartrons",
    category: "contemporary",
    heroImage: "https://cent33.com/wp-content/uploads/2019/11/bannerfb.jpg",
    description:
      "No coração dos Chartrons, o Cent33 combina energia contemporânea, cozinha aberta e uma leitura muito atual da gastronomia bordalesa. É uma escolha excelente para quem quer Michelin com atmosfera menos solene, sem abrir mão de técnica e bons vinhos. O salão tem presença, o bairro convida a caminhar antes ou depois, e o menu costuma funcionar tanto para um jantar especial quanto para uma noite sofisticada entre amigos. Para brasileiros que valorizam experiência visual e serviço atento, é um dos endereços mais completos da cidade.",
    chef: "Fabien Beaufour",
    specialty: "Cozinha criativa contemporânea",
    stars: "1 estrela Michelin",
    michelin: "1 estrela Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Jantar moderno nos Chartrons",
    duration: "2h a 3h",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reservar com antecedência.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.cent33.com/",
    bookingUrl: "https://www.cent33.com/",
    bookingChannel: "Site oficial",
    address: "133 rue du Jardin Public, 33000 Bordeaux",
    coords: { lat: 44.85074, lng: -0.57093 },
    highlights: ["Cozinha aberta", "Mesa Michelin", "Chartrons"],
    seals: ["Michelin", "Escolha QIMO"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(9, 9, 9, 8.9, 9, 8.8, 8, 8.3, 8.9),
    sommelierTip:
      "O estilo contemporâneo permite uma conversa rica com o sommelier. Explore brancos de Bordeaux para entradas, depois tintos de Saint-Émilion ou Pomerol em safras mais acessíveis ao paladar.",
    sourcePrimary: "https://www.cent33.com/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    sortOrder: 7,
  },
  {
    slug: "la-table-dhotes-le-quatrieme-mur",
    name: "La Table d'Hôtes - Le Quatrième Mur",
    city: "Bordeaux",
    neighborhood: "Grand Théâtre",
    category: "michelin",
    heroImage: "https://quatrieme-mur.com/wp-content/uploads/2025/12/1_DSC0918-SD-2.jpg",
    description:
      "Dentro do universo do Le Quatrième Mur, no Grand Théâtre, La Table d'Hôtes é a experiência mais exclusiva ligada a Philippe Etchebest. O formato aproxima o cliente da cozinha e transforma a refeição em encontro gastronômico, com número limitado de lugares e clima de bastidor sofisticado. É uma opção preciosa para quem quer uma experiência Michelin em endereço central e simbólico, especialmente se a viagem combina cultura, ópera, arquitetura e gastronomia. A logística é simples, mas a reserva costuma exigir planejamento.",
    chef: "Philippe Etchebest",
    specialty: "Mesa gastronômica contemporânea",
    stars: "1 estrela Michelin",
    michelin: "1 estrela Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Experiência exclusiva no Grand Théâtre",
    duration: "2h30 a 3h",
    dressCode: "Elegante casual",
    reservationRequired: true,
    reservationAdvice: "Reservar com bastante antecedência.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.quatrieme-mur.com/",
    bookingUrl: "https://www.quatrieme-mur.com/",
    bookingChannel: "Site oficial",
    address: "2 place de la Comédie, 33000 Bordeaux",
    coords: { lat: 44.84214, lng: -0.5747 },
    highlights: ["Mesa do chef", "Grand Théâtre", "Experiência Michelin"],
    seals: ["Michelin", "Reserva concorrida"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(9, 8.8, 9.1, 8.8, 9.9, 9.2, 7.8, 7.8, 8.9),
    sommelierTip:
      "Como o menu é conduzido pela cozinha, informe preferências de corpo e maturidade. Bordeaux branco seco pode surpreender no início; para carnes, peça margem direita com taninos macios.",
    sourcePrimary: "https://www.quatrieme-mur.com/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 8,
  },
  {
    slug: "le-chapon-fin",
    name: "Le Chapon Fin",
    city: "Bordeaux",
    neighborhood: "Triangle d'Or",
    category: "bistro",
    heroImage: "https://ugc.zenchef.com/3/5/1/8/6/1/1/5/0/6/5/8/6/1726652607_328/57e2e21bc05df2d2c24b033790a726f5.website.jpg",
    description:
      "Fundado em 1825, o Le Chapon Fin é uma peça da memória gastronômica de Bordeaux. Seu salão em gruta rococó cria um cenário raro, quase teatral, ideal para viajantes que gostam de restaurantes com história. Hoje a visita vale menos pela busca de vanguarda e mais pela combinação de patrimônio, cozinha francesa, carta de vinhos e localização central. É um endereço interessante para almoço elegante ou jantar clássico, especialmente para quem quer sentir a continuidade das grandes mesas burguesas da cidade.",
    chef: NAO_DIVULGADO,
    specialty: "Cozinha francesa clássica",
    averageTicket: "€50 a €100",
    priceBand: "€50 a €100",
    bestFor: "Clássico histórico de Bordeaux",
    duration: "1h30 a 2h30",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reserva recomendada.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.chapon-fin.com/",
    bookingUrl: "https://www.chapon-fin.com/",
    bookingChannel: "Site oficial",
    phone: "+33556791010",
    address: "5 rue Montesquieu, 33000 Bordeaux",
    coords: { lat: 44.8427, lng: -0.57785 },
    highlights: ["Ambiente histórico", "Cozinha francesa", "Centro"],
    seals: ["Clássico de Bordeaux", "Experiência romântica"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(8.2, 8.7, 9.4, 8.4, 9.6, 8.5, 8, 8.4, 8.5),
    sommelierTip:
      "Use a carta para revisitar clássicos: Médoc para carnes e molhos, Saint-Émilion para pratos mais aveludados e Sauternes com foie gras quando disponível no menu.",
    sourcePrimary: "https://www.chapon-fin.com/",
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 9,
  },
  {
    slug: "la-tupina",
    name: "La Tupina",
    city: "Bordeaux",
    neighborhood: "Saint-Michel",
    category: "bistro",
    heroImage: "https://cdn.prod.website-files.com/66d8a8282153c381a88b3e34/66d8a8e08ef13e7302a3f5dc_Los%20Andes%20Agency3586.jpg",
    description:
      "La Tupina é uma instituição do Sudoeste francês: lareira acesa, produtos regionais, pato, carnes, batatas na gordura e uma atmosfera calorosa que contrasta com a formalidade das mesas Michelin. Para brasileiros, é talvez o melhor endereço para entender a cozinha bordalesa de raiz em uma refeição franca e generosa. A casa funciona muito bem para almoço de domingo, jantar entre amigos ou uma noite de sabores regionais depois de dias de degustação em châteaux. Reserve, porque o nome continua muito procurado.",
    chef: "Fundada por Jean-Pierre Xiradakis; chef atual não divulgado oficialmente.",
    specialty: "Cozinha do Sudoeste francês",
    averageTicket: "€50 a €100",
    priceBand: "€50 a €100",
    bestFor: "Cozinha regional com atmosfera local",
    duration: "1h30 a 2h",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reserva recomendada.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.latupina.com/",
    bookingUrl: "https://www.latupina.com/",
    bookingChannel: "Site oficial",
    phone: "+33556915637",
    address: "6 rue Porte de la Monnaie, 33800 Bordeaux",
    coords: { lat: 44.83376, lng: -0.56355 },
    highlights: ["Cozinha regional", "Lareira", "Clássico bordalês"],
    seals: ["Clássico de Bordeaux", "Experiência local", "Escolha QIMO"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(8.5, 8.6, 9.1, 8.3, 8.8, 8.1, 8.2, 8.5, 8.6),
    sommelierTip:
      "Para pato, carnes e sabores de lareira, peça tintos de estrutura média: Fronsac, Castillon, Graves tinto ou Médoc com alguns anos. Evite vinhos excessivamente alcoólicos se o prato já for rico.",
    sourcePrimary: "https://www.latupina.com/",
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    sortOrder: 10,
  },
  {
    slug: "le-bouchon-bordelais",
    name: "Le Bouchon Bordelais",
    city: "Bordeaux",
    neighborhood: "Triangle d'Or",
    category: "bistro",
    heroImage: "https://assets2.justacote.com/photos_entreprises/le-bouchon-bordelais-bordeaux-14589073900.jpg",
    description:
      "Pequeno, central e muito procurado, o Le Bouchon Bordelais traduz a cozinha regional em formato de bistrô contemporâneo. É uma excelente escolha para quem quer uma refeição francesa sem entrar no ritual longo da alta gastronomia. O menu muda conforme a estação e costuma privilegiar produtos locais, pratos de sabor claro e boa relação com a carta de vinhos. Por estar perto das áreas mais elegantes do centro, encaixa bem em um dia de compras, passeio arquitetônico ou noite mais descontraída.",
    chef: NAO_DIVULGADO,
    specialty: "Bistrô francês e cozinha bordalesa",
    averageTicket: "€50 a €100",
    priceBand: "€50 a €100",
    bestFor: "Bistrô central com boa cozinha",
    duration: "1h30 a 2h",
    dressCode: "Casual",
    reservationRequired: true,
    reservationAdvice: "Reserva recomendada; salão compacto.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.lebouchonbordelais.com/",
    bookingUrl: "https://www.lebouchonbordelais.com/",
    bookingChannel: "Site oficial",
    address: "2 rue Courbin, 33000 Bordeaux",
    coords: { lat: 44.84293, lng: -0.57534 },
    highlights: ["Bistrô", "Cozinha francesa", "Centro"],
    seals: ["Melhor custo-benefício", "Experiência local"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(8.3, 8.4, 8.1, 8.1, 9.6, 7.4, 8.6, 8.2, 8.3),
    sommelierTip:
      "Perfeito para descobrir Bordeaux menos óbvio em taça ou garrafa: Côtes de Bourg, Castillon, Entre-deux-Mers branco e Graves tinto para pratos de bistrô.",
    sourcePrimary: "https://www.lebouchonbordelais.com/",
    sourceSecondary: ["https://www.decanter.com/wine-travel/bordeaux-travel-where-to-eat-and-drink-like-a-local-in-this-famous-wine-region"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 11,
  },
  {
    slug: "bo-tannique",
    name: "Bo-Tannique",
    city: "Bordeaux",
    neighborhood: "Hôtel de Ville",
    category: "bistro",
    heroImage: "https://www.bo-tannique.com/media/cache/resolve/l1200/websites/9b8c5a4f39efed2620297d5ac9cb07b5/img/la-salle-le-bar-et-la_20221006155414.jpg",
    description:
      "Bo-Tannique é um bistrô atual, sazonal e muito útil para quem quer comer bem no centro sem transformar a refeição em evento formal. A cozinha valoriza produto, frescor e pratos bem acabados, com atmosfera local e bom encaixe para almoço. É uma boa recomendação para viajantes que apreciam restaurantes de bairro com ambição, serviço simpático e carta de vinhos interessante. Funciona especialmente bem entre visitas culturais, compras e caminhadas pelo miolo histórico.",
    chef: NAO_DIVULGADO,
    specialty: "Bistrô contemporâneo sazonal",
    averageTicket: "€50 a €100",
    priceBand: "€50 a €100",
    bestFor: "Almoço no centro",
    duration: "1h15 a 2h",
    dressCode: "Casual",
    reservationRequired: true,
    reservationAdvice: "Reserva recomendada.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.bo-tannique.com/",
    bookingUrl: "https://www.bo-tannique.com/",
    bookingChannel: "Site oficial",
    address: "2 rue Tustal, 33000 Bordeaux",
    coords: { lat: 44.83756, lng: -0.57771 },
    highlights: ["Cozinha sazonal", "Almoço", "Centro histórico"],
    seals: ["Melhor custo-benefício", "Almoço imperdível"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(8.2, 8.2, 8, 8.1, 9.2, 7.2, 8.7, 8.2, 8.2),
    sommelierTip:
      "Para menus sazonais, peça vinhos vivos e versáteis: Entre-deux-Mers, Graves branco, Bordeaux Supérieur de produtores menores ou tintos de Castillon.",
    sourcePrimary: "https://www.bo-tannique.com/",
    sourceSecondary: ["https://www.decanter.com/wine-travel/bordeaux-travel-where-to-eat-and-drink-like-a-local-in-this-famous-wine-region"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 12,
  },
  {
    slug: "le-bar-a-vin-du-civb",
    name: "Le Bar à Vin du CIVB",
    city: "Bordeaux",
    neighborhood: "Triangle d'Or",
    category: "wine-bar",
    heroImage: "https://www.bordeaux.com/app/uploads/2025/12/bar-a-vin_gbonnaud_civb2021-21-1-1.jpg",
    description:
      "Administrado pelo Conseil Interprofessionnel du Vin de Bordeaux, o Bar à Vin é a porta de entrada mais didática para entender a diversidade da região. O ambiente é elegante, os preços costumam ser convidativos e a seleção permite provar taças de diferentes denominações sem compromisso de jantar completo. É ideal para o primeiro dia na cidade, antes de visitar châteaux, ou para calibrar preferências entre margem esquerda, margem direita, brancos secos e doces. Não substitui um grande restaurante, mas cumpre muito bem a função de introdução ao vinho bordalês.",
    chef: "Não se aplica.",
    specialty: "Wine bar oficial dos vinhos de Bordeaux",
    averageTicket: "Até €50",
    priceBand: "Até €50",
    bestFor: "Degustação leve antes do jantar",
    duration: "45min a 1h30",
    dressCode: "Casual elegante",
    reservationRequired: false,
    reservationAdvice: "Chegar cedo em horários de pico.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.baravin.bordeaux.com/",
    bookingUrl: "",
    bookingChannel: "Atendimento no local",
    address: "3 cours du 30 Juillet, 33000 Bordeaux",
    coords: { lat: 44.84374, lng: -0.57535 },
    highlights: ["Taças de Bordeaux", "Didático", "Centro"],
    seals: ["Melhor carta de vinhos", "Melhor custo-benefício", "Experiência local"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: "Há acompanhamentos simples; cardápio completo deve ser confirmado no local.",
      groups: NAO_DIVULGADO,
      prepayment: "Não divulgado oficialmente.",
      status: "Aberto conforme site oficial consultado.",
      reservationStatus: "Reserva online não identificada.",
    },
    qimoScores: score(7.4, 9.4, 8.5, 8, 9.8, 7.3, 9.3, 7.6, 8.5),
    sommelierTip:
      "Use a visita como mapa sensorial: prove um branco seco, um Saint-Émilion, um Médoc e um Sauternes em pequenas taças. Anote o estilo preferido antes das compras.",
    sourcePrimary: "https://www.baravin.bordeaux.com/",
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    sortOrder: 13,
  },
  {
    slug: "wine-more-time",
    name: "Wine More Time",
    city: "Bordeaux",
    neighborhood: "Grosse Cloche",
    category: "wine-bar",
    heroImage: "https://winemoretime.fr/wp-content/uploads/2020/11/IMG_6326-2048x1150.jpg",
    description:
      "Wine More Time é um wine bar descontraído e inteligente, perfeito para quem quer sair do circuito mais formal e provar garrafas com curadoria. A localização perto da Grosse Cloche favorece uma parada no fim da tarde, com tábuas, queijos, charcuterie e uma conversa mais solta sobre produtores. Para o público QIMO, funciona bem como experiência leve entre almoço e jantar ou como noite informal depois de um dia de visitas. O interesse está na descoberta e na hospitalidade, não no luxo clássico.",
    chef: "Não se aplica.",
    specialty: "Wine bar, queijos, charcuterie e pequenos pratos",
    averageTicket: "Até €50",
    priceBand: "Até €50",
    bestFor: "Taças e petiscos no fim da tarde",
    duration: "1h a 2h",
    dressCode: "Casual",
    reservationRequired: false,
    reservationAdvice: "Entrar em contato para grupos.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.winemoretime.fr/",
    bookingUrl: "https://www.winemoretime.fr/",
    bookingChannel: "Site oficial / contato",
    address: "8 rue Saint-James, 33000 Bordeaux",
    coords: { lat: 44.83749, lng: -0.57078 },
    highlights: ["Wine bar", "Produtores locais", "Ambiente descontraído"],
    seals: ["Experiência local", "Melhor carta de vinhos"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: "Ambiente mais indicado para adultos.",
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Contato pelo site oficial.",
    },
    qimoScores: score(7.6, 8.9, 8.2, 8.2, 9.1, 7.1, 8.8, 7.8, 8.2),
    sommelierTip:
      "Peça para montar uma sequência por margem: esquerda, direita e uma denominação satélite. É uma forma simples de entender taninos, fruta e estrutura antes de comprar garrafas.",
    sourcePrimary: "https://www.winemoretime.fr/",
    sourceSecondary: ["https://www.decanter.com/wine-travel/bordeaux-travel-where-to-eat-and-drink-like-a-local-in-this-famous-wine-region"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 14,
  },
  {
    slug: "complanterra",
    name: "ComplanTerra",
    city: "Bordeaux",
    neighborhood: "Saint-Pierre",
    category: "wine-bar",
    heroImage: "https://www.complanterra.fr/web/image/11842-ad4d8cbe/2bb55bc2-34ee-40bb-8394-c54afddc9bf7.JPG",
    description:
      "ComplanTerra é uma boa parada para viajantes curiosos por vinhos orgânicos, biodinâmicos e produtores de menor escala. O ambiente é mais informal e contemporâneo, com foco em descoberta e conversa, e combina bem com uma noite leve no centro histórico. Em vez de procurar rótulos consagrados, vale deixar a equipe guiar a seleção por estilo, região e energia do vinho. Para quem já conhece os grandes nomes de Bordeaux, é um contraponto interessante e menos previsível.",
    chef: "Não se aplica.",
    specialty: "Wine bar com foco em vinhos orgânicos e biodinâmicos",
    averageTicket: "Até €50",
    priceBand: "Até €50",
    bestFor: "Descoberta de produtores",
    duration: "1h a 2h",
    dressCode: "Casual",
    reservationRequired: false,
    reservationAdvice: "Entrar em contato para grupos.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.complanterra.fr/",
    bookingUrl: "https://www.complanterra.fr/",
    bookingChannel: "Site oficial / contato",
    address: "42 rue Sainte-Colombe, 33000 Bordeaux",
    coords: { lat: 44.8362, lng: -0.56911 },
    highlights: ["Vinhos biodinâmicos", "Wine bar", "Centro histórico"],
    seals: ["Experiência local", "Melhor carta de vinhos"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: "Ambiente mais indicado para adultos.",
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Contato pelo site oficial.",
    },
    qimoScores: score(7.4, 9.1, 8, 8.1, 9.1, 7.3, 8.6, 7.7, 8.2),
    sommelierTip:
      "Peça vinhos de agricultura orgânica de Castillon, Francs, Bourg ou Graves. A conversa fica melhor quando você descreve textura desejada: fresco, mineral, frutado ou estruturado.",
    sourcePrimary: "https://www.complanterra.fr/",
    sourceSecondary: ["https://www.decanter.com/wine-travel/bordeaux-travel-where-to-eat-and-drink-like-a-local-in-this-famous-wine-region"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 15,
  },
  {
    slug: "couleurs-du-vin",
    name: "Couleurs du Vin",
    city: "Bordeaux",
    neighborhood: "Chartrons",
    category: "wine-bar",
    heroImage: "https://privateaser-media.s3.eu-west-1.amazonaws.com/etab_photos/51356/750x375/608691.jpg",
    description:
      "Couleurs du Vin combina loja, degustação e conversa especializada, com uma abordagem útil para quem quer comprar garrafas em Bordeaux sem depender apenas de nomes famosos. A experiência é menos restaurante e mais curadoria de vinho: boa para uma pausa nos Chartrons, bairro historicamente ligado ao comércio vinícola. Para hóspedes que pretendem levar garrafas ou entender melhor denominações, vale pedir uma seleção por orçamento, ocasião e capacidade de guarda.",
    chef: "Não se aplica.",
    specialty: "Cave e degustação de vinhos",
    averageTicket: "Até €50",
    priceBand: "Até €50",
    bestFor: "Degustação e compra de vinhos",
    duration: "45min a 1h30",
    dressCode: "Casual",
    reservationRequired: false,
    reservationAdvice: "Entrar em contato para degustações ou grupos.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.couleursduvin.com/",
    bookingUrl: "https://www.couleursduvin.com/",
    bookingChannel: "Site oficial / contato",
    address: "4 rue Borie, 33300 Bordeaux",
    coords: { lat: 44.85402, lng: -0.56839 },
    highlights: ["Cave", "Degustação", "Chartrons"],
    seals: ["Melhor carta de vinhos", "Experiência local"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: "Não se aplica.",
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Contato pelo site oficial.",
    },
    qimoScores: score(6.8, 8.8, 7.8, 8.2, 8.7, 7.1, 8.5, 7.8, 8),
    sommelierTip:
      "Diga se as garrafas serão consumidas na viagem ou levadas ao Brasil. Isso muda a escolha entre vinhos prontos, safras de guarda e formatos mais fáceis de transportar.",
    sourcePrimary: "https://www.couleursduvin.com/",
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 16,
  },
  {
    slug: "marche-des-capucins",
    name: "Marché des Capucins",
    city: "Bordeaux",
    neighborhood: "Capucins",
    category: "contemporary",
    heroImage: "https://image.jimcdn.com/app/cms/image/transf/none/path/sa6549607c78f5c11/image/iac0c115f7b8dde59/version/1452877405/image.jpg",
    description:
      "O Marché des Capucins é a experiência gastronômica mais autêntica de Bordeaux para quem gosta de mercados. Ostras, queijos, pães, produtos bascos, cafés e balcões informais formam um retrato vivo da cidade fora dos salões gastronômicos. Não é um restaurante único, mas um conjunto de bancas e pequenos endereços que funcionam melhor pela manhã ou no almoço. Para a QIMO, é uma parada excelente para sentir o cotidiano local, provar ostras com vinho branco e comprar produtos regionais.",
    chef: "Não se aplica.",
    specialty: "Mercado gastronômico, ostras e produtos regionais",
    averageTicket: "Até €50",
    priceBand: "Até €50",
    bestFor: "Manhã de mercado e almoço informal",
    duration: "1h a 2h",
    dressCode: "Casual",
    reservationRequired: false,
    reservationAdvice: "Não depende de reserva; chegar cedo para melhor experiência.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.marchedescapucins.com/",
    bookingUrl: "",
    bookingChannel: "Atendimento no local",
    address: "Place des Capucins, 33800 Bordeaux",
    coords: { lat: 44.83075, lng: -0.56879 },
    highlights: ["Mercado", "Ostras", "Experiência local"],
    seals: ["Experiência local", "Almoço imperdível", "Melhor custo-benefício"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: "Adequado para famílias que apreciam mercados movimentados.",
      vegetarian: "Há opções de mercado, mas varia por banca.",
      groups: "Grupos devem circular em pequenos núcleos.",
      prepayment: "Não se aplica.",
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Sem reserva online para o mercado.",
    },
    qimoScores: score(8, 8.1, 8.2, 7.5, 8.5, 6.8, 9.2, 9, 8.3),
    sommelierTip:
      "Com ostras, peça branco seco de Entre-deux-Mers ou Graves. Para compras, procure Sauternes em meia garrafa e queijos locais para uma degustação no hotel.",
    sourcePrimary: "https://www.marchedescapucins.com/",
    sourceSecondary: ["https://www.decanter.com/wine-travel/bordeaux-travel-where-to-eat-and-drink-like-a-local-in-this-famous-wine-region"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    qimoSelect: true,
    sortOrder: 17,
  },
  {
    slug: "symbiose",
    name: "Symbiose",
    city: "Bordeaux",
    neighborhood: "Quais",
    category: "contemporary",
    heroImage: "https://symbiose-bordeaux.com/images/symbiose-restaurant.jpg",
    description:
      "Symbiose une coquetelaria, cozinha contemporânea e clima urbano perto dos quais. É uma alternativa interessante para quem já teve dias de grandes menus e quer uma noite mais livre, com bons drinques, pratos criativos e atmosfera jovem sem perder qualidade. A casa conversa com a Bordeaux atual: menos formal, mais social, ainda ligada ao produto e ao prazer à mesa. Para hóspedes 40+, funciona melhor como jantar descontraído ou parada antes de uma caminhada à beira do Garonne.",
    chef: NAO_DIVULGADO,
    specialty: "Cozinha contemporânea e coquetelaria",
    averageTicket: "€50 a €100",
    priceBand: "€50 a €100",
    bestFor: "Jantar descontraído com coquetéis",
    duration: "1h30 a 2h30",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reserva recomendada para jantar.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.symbiose-bordeaux.com/",
    bookingUrl: "https://www.symbiose-bordeaux.com/",
    bookingChannel: "Site oficial",
    address: "4 quai des Chartrons, 33000 Bordeaux",
    coords: { lat: 44.84916, lng: -0.56845 },
    highlights: ["Coquetelaria", "Quais", "Cozinha criativa"],
    seals: ["Experiência local"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: "Ambiente mais indicado para adultos.",
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(8, 8.1, 8.5, 8, 8.8, 7.5, 8.1, 8, 8.1),
    sommelierTip:
      "Se optar por vinho em vez de coquetel, busque brancos secos para pratos leves e tintos de margem direita com fruta para pratos mais intensos.",
    sourcePrimary: "https://www.symbiose-bordeaux.com/",
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 18,
  },
  {
    slug: "solena",
    name: "Soléna",
    city: "Bordeaux",
    neighborhood: "Saint-Seurin",
    category: "contemporary",
    heroImage: "https://prod-pics.guide.michelin.com/api/public/content/00df0fe3f9464c72b0d3e3fb798ca065.jpg?format=webp",
    description:
      "Soléna é uma mesa gastronômica moderna que combina técnica, delicadeza e ambiente acolhedor. O restaurante é uma boa alternativa para quem deseja alta qualidade sem a cerimônia dos grandes hotéis. A cozinha favorece menus trabalhados, bom produto e uma leitura contemporânea que se mantém acessível para quem aprecia sofisticação discreta. Por estar fora do circuito mais óbvio do centro turístico, pode ser uma escolha acertada para um jantar de casal ou pequenos grupos que valorizam calma e consistência.",
    chef: "Victor Ostronzec",
    specialty: "Cozinha gastronômica moderna",
    stars: "1 estrela Michelin",
    michelin: "1 estrela Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Jantar gastronômico discreto",
    duration: "2h a 3h",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reservar com antecedência.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://www.solena-restaurant.com/",
    bookingUrl: "https://www.solena-restaurant.com/",
    bookingChannel: "Site oficial",
    address: "5 rue Chauffour, 33000 Bordeaux",
    coords: { lat: 44.84078, lng: -0.58865 },
    highlights: ["Mesa Michelin", "Cozinha moderna", "Ambiente discreto"],
    seals: ["Michelin", "Experiência romântica"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(8.8, 8.6, 8.4, 8.6, 8.2, 8.3, 8, 8, 8.6),
    sommelierTip:
      "Peça uma harmonização por textura. Para pratos delicados, brancos secos; para carnes e reduções, Pomerol ou Saint-Émilion com taninos arredondados.",
    sourcePrimary: "https://www.solena-restaurant.com/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 19,
  },
  {
    slug: "tentazioni",
    name: "Tentazioni",
    city: "Bordeaux",
    neighborhood: "Chartrons",
    category: "contemporary",
    heroImage: "https://tentazioni-bordeaux.com/wp-content/uploads/2024/10/tentazioni-10.jpg",
    description:
      "Tentazioni oferece um desvio italiano de alto nível dentro da cena gastronômica de Bordeaux. A casa é interessante para viajantes que já fizeram muitos menus franceses e querem uma noite sofisticada, mas com outra matriz culinária. A cozinha italiana contemporânea, quando bem executada, conversa muito bem com Bordeaux: acidez, massas, mar, queijos e molhos pedem escolhas de vinho mais precisas. É uma opção elegante para alternar o repertório da viagem sem perder padrão de serviço e curadoria.",
    chef: NAO_DIVULGADO,
    specialty: "Cozinha italiana contemporânea",
    stars: "1 estrela Michelin",
    michelin: "1 estrela Michelin",
    averageTicket: "Acima de €100",
    priceBand: "Acima de €100",
    bestFor: "Alternativa italiana sofisticada",
    duration: "2h a 3h",
    dressCode: "Casual elegante",
    reservationRequired: true,
    reservationAdvice: "Reserva recomendada.",
    days: NAO_DIVULGADO,
    hours: NAO_DIVULGADO,
    website: "https://tentazioni-bordeaux.com/",
    bookingUrl: "https://tentazioni-bordeaux.com/",
    bookingChannel: "Site oficial",
    address: "59 rue du Palais Gallien, 33000 Bordeaux",
    coords: { lat: 44.84637, lng: -0.58094 },
    highlights: ["Mesa Michelin", "Cozinha italiana", "Jantar sofisticado"],
    seals: ["Michelin", "Experiência romântica"],
    practical: {
      accessibility: NAO_DIVULGADO,
      children: NAO_DIVULGADO,
      vegetarian: NAO_DIVULGADO,
      groups: NAO_DIVULGADO,
      prepayment: NAO_DIVULGADO,
      status: "Aberto conforme presença oficial consultada.",
      reservationStatus: "Reserva pelo site oficial.",
    },
    qimoScores: score(8.7, 8.4, 8.5, 8.5, 8.7, 8.2, 7.9, 8, 8.5),
    sommelierTip:
      "Mesmo em cozinha italiana, Bordeaux funciona: brancos de Graves com frutos do mar, Saint-Émilion para massas com cogumelos e Sauternes apenas se houver queijos ou sobremesas adequadas.",
    sourcePrimary: "https://tentazioni-bordeaux.com/",
    sourceSecondary: ["https://guide.michelin.com/"],
    lastVerified: "2026-07-11",
    informationStatus: "parcial",
    adminStatus: "ativo",
    sortOrder: 20,
  },
];
