import type { Restaurant } from "@/lib/types";

// Restaurantes — canais oficiais de reserva verificados (jul/2026)
export const restaurants: Restaurant[] = [
  {
    slug: "le-pressoir-dargent",
    name: "Le Pressoir d'Argent — Gordon Ramsay",
    city: "Bordeaux",
    heroImage: "/photos/food-entrecote.jpg",
    description:
      "A mesa de alta gastronomia de Gordon Ramsay no InterContinental, célebre pela prensa de lagosta em prata maciça (uma de apenas cinco no mundo) usada na sala.",
    chef: "Gordon Ramsay",
    specialty: "Alta gastronomia · frutos do mar, trufa e foie gras",
    stars: "2 estrelas Michelin",
    averageTicket: "€€€€ · menus a partir de ~€ 165",
    dressCode: "Elegante (recomenda-se paletó)",
    reservationRequired: true,
    days: "Terça a sábado, jantar (19h–21h30)",
    website: "https://bordeaux.intercontinental.com/le-pressoir-dargent-gordon-ramsay/",
    bookingUrl: "https://www.thefork.fr/restaurant/le-pressoir-d-argent-gordon-ramsay-intercontinental-bordeaux-r750552",
    bookingChannel: "TheFork",
    phone: "+33557304444",
    address: "2 place de la Comédie, 33000 Bordeaux",
    qimoSelect: true,
  },
  {
    slug: "la-tupina",
    name: "La Tupina",
    city: "Bordeaux",
    heroImage: "/photos/food-magret.jpg",
    description:
      "Instituição de Bordeaux desde 1968, alma da cozinha do Sudoeste: grelhados na lareira, magret, batatas na gordura de pato e frango na chaminé.",
    chef: "Franck Audu (fundada por Jean-Pierre Xiradakis)",
    specialty: "Cozinha do Sudoeste francês",
    averageTicket: "€€€ · almoço a partir de € 18",
    dressCode: "Casual elegante",
    reservationRequired: true,
    days: "Jantar todos os dias; almoço de terça a domingo",
    website: "https://www.latupina.com/",
    bookingUrl: "https://www.thefork.fr/restaurant/la-tupina-r184",
    bookingChannel: "TheFork",
    phone: "+33556915637",
    address: "6 rue Porte-de-la-Monnaie, 33800 Bordeaux",
    qimoSelect: true,
  },
  {
    slug: "le-chapon-fin",
    name: "Le Chapon Fin",
    city: "Bordeaux",
    heroImage: "/photos/food-foiegras.jpg",
    description:
      "Fundado em 1825, no coração do Triângulo de Ouro, com seu célebre salão rococó em gruta. Um dos restaurantes históricos da França.",
    specialty: "Cozinha francesa clássica",
    averageTicket: "€€€",
    dressCode: "Casual elegante",
    reservationRequired: true,
    website: "https://www.chapon-fin.com/en/",
    bookingUrl: "https://www.thefork.fr/restaurant/le-chapon-fin-r210107",
    bookingChannel: "TheFork",
    phone: "+33556791010",
    address: "5 rue Montesquieu, 33000 Bordeaux",
  },
  {
    slug: "logis-de-la-cadene",
    name: "Logis de la Cadène",
    city: "Saint-Émilion",
    heroImage: "/photos/food-queijos.jpg",
    description:
      "O mais antigo restaurante de Saint-Émilion (1848), no coração da vila medieval, sob uma pérgola de glicínias. Cozinha refinada de vegetais e mar.",
    chef: "Thibaut Gamba",
    specialty: "Gastronômico · vegetais e frutos do mar",
    stars: "1 estrela Michelin",
    averageTicket: "€€€€",
    dressCode: "Casual elegante",
    reservationRequired: true,
    days: "Terça a sexta (almoço e jantar); sábado (jantar)",
    website: "https://www.logisdelacadene.fr/en/",
    bookingUrl: "https://www.logisdelacadene.fr/en/",
    bookingChannel: "Site oficial",
    phone: "+33557247140",
    address: "3 place du Marché au Bois, 33330 Saint-Émilion",
    qimoSelect: true,
  },
  {
    slug: "lenvers-du-decor",
    name: "L'Envers du Décor",
    city: "Saint-Émilion",
    heroImage: "/photos/food-canele.jpg",
    description:
      "Wine bar e bistrô no centro de Saint-Émilion, da família Perse (Château Pavie). Cozinha de mercado e uma carta de vinhos excepcional.",
    chef: "Bertrand Bordenave",
    specialty: "Bistrô · cozinha de mercado & vinhos",
    averageTicket: "€€–€€€",
    dressCode: "Casual",
    reservationRequired: true,
    days: "Todos os dias · 12h–14h e 19h–21h30",
    website: "https://www.envers-dudecor.com/",
    bookingUrl: "https://www.envers-dudecor.com/contact/",
    bookingChannel: "Site oficial / e-mail",
    email: "reservation@envers-dudecor.com",
    phone: "+33557744831",
    address: "9 rue du Clocher, 33330 Saint-Émilion",
  },
];
