import type { Winery } from "@/lib/types";

export const wineries: Winery[] = [
  {
    slug: "grand-puy-ducasse",
    name: "Château Grand-Puy-Ducasse",
    heroImage: "https://grandpuyducasse.fr/wp-content/uploads/2024/07/facade-de-GPD.jpg",
    appellation: "Pauillac",
    classification: "5º Grand Cru Classé (1855)",
    family: "CA Grands Crus (Grupo Crédit Agricole), desde 2004",
    history:
      "Nascido no século XVIII quando Pierre Ducasse reuniu parcelas no platô do Grand-Puy, o château foi classificado como 5º Cru na hierarquia de 1855. Desde 2004 pertence à CA Grands Crus (Grupo Crédit Agricole). Suas vinhas estão espalhadas em três setores de cascalho profundo de Pauillac, enquanto o château histórico se ergue à beira do Gironde, no cais de Pauillac — caso raro de um Grand Cru com sede à beira-rio.",
    terroir: "Croupes de cascalho garonês (graves) sobre subsolo calcário, drenagem excepcional.",
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"],
    production: "Cerca de 20 mil caixas/ano.",
    icons: ["Château Grand-Puy-Ducasse (grand vin)", "Prélude à Grand-Puy-Ducasse (segundo vinho)"],
    scores: [
      { critic: "James Suckling", note: "95 pts · safra 2019" },
      { critic: "Wine Spectator", note: "93 pts · safra 2019" },
      { critic: "Decanter", note: "92 pts · safra 2019" },
    ],
    averagePrice: "€ 45–70 a garrafa (grand vin, safras recentes).",
    whatToBuy: ["Grand vin de uma grande safra (2016, 2018, 2019, 2020)", "O segundo vinho 'Prélude' para beber mais cedo"],
    whatToTaste: ["Cassis e grafite típicos de Pauillac", "Taninos firmes e final mentolado"],
    curiosities: [
      "É um dos poucos Grands Crus com château no coração da cidade de Pauillac.",
      "Passou por profunda renovação técnica nas últimas décadas.",
    ],
    visitHours: "Visita privativa QIMO — tarde do Dia 2 (26/10).",
    dressCode: "Casual elegante.",
    website: "https://grandpuyducasse.fr/en/",
    bookingUrl: "https://grandpuyducasse-renaissance.fr/en/",
    bookingChannel: "Reserva oficial (espaço Renaissance)",
    address: "4 Quai Antoine Ferchaud, 33250 Pauillac",
    coords: { lat: 45.2003, lng: -0.7458 },
    qimoSelect: true,
    visitedOnDays: [2],
  },
  {
    slug: "pedesclaux",
    name: "Château Pédesclaux",
    heroImage: "https://www.chateau-pedesclaux.com/wp-content/uploads/2020/08/9ddd0758c4d343179e20a10d70be874c-1920x1280.jpeg",
    appellation: "Pauillac",
    classification: "5º Grand Cru Classé (1855)",
    family: "Família Lorenzetti",
    history:
      "Fundado em 1810 por Urbain-Pierre Pédesclaux, corretor de vinhos, e classificado 5º Cru em 1855. Após décadas de discrição, uma aquisição em 2009 e um investimento monumental transformaram o château: uma cave gravitacional envolta em uma 'caixa' de vidro, assinada pelo arquiteto Jean-Michel Wilmotte, hoje é um dos gestos arquitetônicos mais ousados do Médoc.",
    terroir: "Cascalho profundo de Pauillac, parcelas vizinhas às de grandes crus consagrados.",
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot", "Cabernet Franc"],
    production: "Cerca de 20 mil caixas/ano.",
    icons: ["Château Pédesclaux (grand vin)", "Fleur de Pédesclaux (segundo vinho)"],
    scores: [
      { critic: "James Suckling", note: "91 pts · safra 2019" },
      { critic: "Média da crítica", note: "≈ 92 pts · safras 2019–2020" },
    ],
    averagePrice: "€ 40–65 a garrafa.",
    whatToBuy: ["Grand vin pós-2014 (após a reformulação)", "Fleur de Pédesclaux para consumo mais próximo"],
    whatToTaste: ["Fruta preta madura", "Estrutura moderna, polida e precisa"],
    curiosities: [
      "A adega envidraçada de Wilmotte 'flutua' sobre o château histórico.",
      "Vinificação por gravidade, parcela a parcela.",
    ],
    visitHours: "Visita privativa QIMO — tarde do Dia 2 (26/10).",
    dressCode: "Casual elegante.",
    website: "https://www.chateau-pedesclaux.com/en/",
    bookingUrl: "https://www.chateau-pedesclaux.com/en/contact/",
    bookingChannel: "Formulário oficial de visita",
    address: "Route de la Rivière, 33250 Pauillac",
    coords: { lat: 45.2075, lng: -0.7539 },
    qimoSelect: true,
    visitedOnDays: [2],
  },
  {
    slug: "sauternes-cadillac",
    name: "Sauternes — o brinde de Cadillac",
    heroImage: "https://www.chateaudecazeneuve.com/medias/images/bandeau/accueil-3.jpg",
    appellation: "Sauternes",
    classification: "Vinho doce botritizado",
    history:
      "No Dia 3, o brinde no Château Royal de Cazeneuve celebra o mais famoso vinho doce do mundo. Sauternes nasce da 'podridão nobre' (Botrytis cinerea), um fungo que, em outonos de manhãs úmidas e tardes secas na confluência do Ciron com a Garonne, desidrata as uvas e concentra açúcares e aromas em níveis extraordinários.",
    terroir: "Micro-clima do rio Ciron: névoas matinais que instalam a podridão nobre.",
    grapes: ["Sémillon", "Sauvignon Blanc", "Muscadelle"],
    production: "Rendimentos ínfimos — diz-se que cada videira dá apenas uma taça em Yquem.",
    icons: ["Château d'Yquem (Premier Cru Supérieur)", "Sauternes & Barsac Premiers Crus"],
    scores: [{ critic: "Robert Parker", note: "Os grandes Sauternes figuram entre os vinhos mais bem pontuados do mundo (95–100)." }],
    averagePrice: "€ 30 (entrada) a centenas de euros (grandes casas e safras).",
    whatToBuy: ["Uma meia-garrafa de um bom Sauternes", "Cadillac ou Loupiac como alternativa acessível"],
    whatToTaste: ["Damasco, mel, açafrão e casca de laranja", "Acidez que equilibra a doçura"],
    curiosities: [
      "Serve-se gelado, como aperitivo ou com foie gras e queijos azuis.",
      "Grandes safras podem guardar-se por mais de meio século.",
    ],
    visitHours: "Brinde durante o tour do château — Dia 3 (27/10).",
    website: "https://www.chateaudecazeneuve.com/",
    bookingUrl: "https://www.chateaudecazeneuve.com/fr/visites/individuels.html",
    bookingChannel: "Site oficial de visitas",
    phone: "+33556254816",
    email: "chateaudecazeneuve@orange.fr",
    address: "Château de Cazeneuve, 33730 Préchac",
    coords: { lat: 44.4225, lng: -0.3081 },
    qimoSelect: true,
    visitedOnDays: [3],
  },
  {
    slug: "remy-martin",
    name: "Maison Rémy Martin",
    heroImage: "https://static-prod.remymartin.com/app/uploads/sites/2/2026/05/Remy-Chais-Francis-2-600x600.webp",
    appellation: "Cognac",
    classification: "Fine Champagne Cognac",
    family: "Casa fundada em 1724",
    history:
      "Fundada em 1724 por Rémy Martin, é a única grande casa de Cognac a trabalhar exclusivamente com eaux-de-vie das duas melhores crus — Grande e Petite Champagne (a 'Fine Champagne'). Seu símbolo é o centauro. A visita 'Rendez-Vous Chez Rémy Martin' (Dia 4) revela os segredos do envelhecimento e culmina em uma degustação de conhaques raros.",
    terroir: "Solos calcários de Grande e Petite Champagne, o coração da região de Cognac.",
    grapes: ["Ugni Blanc (para destilação)"],
    production: "Envelhecimento em barris de carvalho do Limousin.",
    icons: ["Rémy Martin VSOP", "Rémy Martin XO", "Louis XIII (em decanter de cristal Baccarat)"],
    averagePrice: "VSOP a partir de € 45; XO cerca de € 150; Louis XIII na casa dos milhares.",
    whatToBuy: ["Rémy Martin XO", "Uma edição de degustação da própria maison"],
    whatToTaste: ["VSOP: baunilha, damasco e carvalho", "XO: figo, avelã, canela e couro"],
    curiosities: [
      "Louis XIII reúne até 1.200 eaux-de-vie, algumas com um século de idade.",
      "O centauro no brasão homenageia o signo de Sagitário do fundador.",
    ],
    visitHours: "Masterpiece Collection — tarde do Dia 4 (28/10).",
    dressCode: "Casual elegante.",
    website: "https://www.remymartin.com",
    bookingUrl: "https://www.remymartin.com/visit-us/",
    bookingChannel: "Reserva oficial de visita",
    phone: "+33545357666",
    address: "20 Rue de la Société Vinicole, 16100 Cognac",
    qimoSelect: true,
    visitedOnDays: [4],
  },
  {
    slug: "saint-emilion-grand-cru",
    name: "Grand Cru de Saint-Émilion",
    heroImage: "https://www.saint-emilion-tourisme.com/media/cache/ogimage/uploads/img/saint-emilion-tourisme-com-65a161889c990278662155.jpg",
    appellation: "Saint-Émilion Grand Cru",
    classification: "Grand Cru Classé",
    history:
      "Na margem direita, o Merlot reina sobre solos de calcário, argila e cascalho. Os grandes crus de Saint-Émilion — de nomes como Cheval Blanc, Ausone, Figeac, Pavie e Angélus — produzem tintos generosos, aveludados e perfumados. No Dia 5, a QIMO reserva degustações e experiências (aula de culinária, piquenique e prova de Grand Cru) em châteaux da denominação.",
    terroir: "Platô e encostas de calcário (côtes) e o cascalho de Figeac, na fronteira com Pomerol.",
    grapes: ["Merlot", "Cabernet Franc", "Cabernet Sauvignon"],
    icons: ["Château Cheval Blanc (Premier Grand Cru Classé A)", "Château Figeac", "Château Angélus"],
    scores: [
      { critic: "Robert Parker", note: "Os Premiers Grands Crus Classés A alcançam 96–100 nas grandes safras." },
      { critic: "James Suckling", note: "Faixa 94–99 para os grandes nomes." },
    ],
    averagePrice: "De € 30 (Saint-Émilion Grand Cru genérico) a milhares (grandes crus).",
    whatToBuy: ["Um Grand Cru Classé de safra madura, pronto para beber", "Um Merlot de encosta calcária"],
    whatToTaste: ["Ameixa, trufa e violeta", "Textura sedosa, taninos macios"],
    curiosities: [
      "A classificação de Saint-Émilion é revista periodicamente — a única que se atualiza.",
      "Cheval Blanc é célebre por seu alto teor de Cabernet Franc.",
    ],
    visitHours: "Experiências QIMO — Dia 5 (29/10).",
    website: "https://www.saint-emilion-tourisme.com/en/",
    bookingUrl: "https://www.saint-emilion-tourisme.com/en/",
    bookingChannel: "Office de Tourisme de Saint-Émilion",
    address: "Saint-Émilion, 33330",
    dressCode: "Casual elegante.",
    coords: { lat: 44.8938, lng: -0.1556 },
    qimoSelect: true,
    visitedOnDays: [5],
  },
];
