import type { Appellation } from "@/lib/types";

export const appellations: Appellation[] = [
  {
    slug: "margaux",
    heroImage: "https://framerusercontent.com/assets/NrmSAGR3eetbhhi5ciounZb7vk.webp",
    name: "Margaux",
    bank: "Left",
    color: "Tinto",
    tagline: "A mais perfumada e elegante das denominações do Médoc",
    description:
      "Terroir de cascalho fino sobre a margem esquerda, Margaux dá tintos de rara finura e perfume floral. É a maior denominação comunal do Médoc e abriga o Premier Cru Château Margaux.",
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot", "Cabernet Franc"],
    profile: "Aromático e sedoso: violeta, frutas vermelhas, especiarias finas. Taninos elegantes.",
    serveTemp: "16–18 °C",
    pairings: ["Cordeiro", "Aves de caça", "Queijos de casca mole"],
    aging: "10–30 anos nas grandes safras.",
    topProducers: ["Château Margaux", "Château Palmer", "Château Rauzan-Ségla"],
  },
  {
    slug: "pauillac",
    heroImage: "https://grandpuyducasse.fr/wp-content/uploads/2024/07/facade-de-GPD.jpg",
    name: "Pauillac",
    bank: "Left",
    color: "Tinto",
    tagline: "Poder e longevidade — três Premiers Crus",
    description:
      "O ápice do Cabernet Sauvignon. Cascalho profundo, tintos estruturados e concentrados, feitos para envelhecer por décadas. Abriga Lafite, Latour e Mouton Rothschild.",
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"],
    profile: "Cassis, grafite, cedro e tabaco. Estrutura firme e final longo.",
    serveTemp: "17–18 °C",
    pairings: ["Entrecôte grelhado", "Cordeiro assado", "Cogumelos e trufas"],
    aging: "15–50 anos nas grandes safras.",
    topProducers: ["Lafite Rothschild", "Latour", "Mouton Rothschild", "Pichon", "Grand-Puy-Ducasse", "Pédesclaux"],
    qimoNote: "Denominação das visitas privativas do Dia 2 (Grand-Puy-Ducasse e Pédesclaux).",
  },
  {
    slug: "saint-julien",
    heroImage: "https://www.beychevelle.com/wp-content/uploads/2025/09/PAGE-ACCEUIL-TERROIR-1-scaled.webp",
    name: "Saint-Julien",
    bank: "Left",
    color: "Tinto",
    tagline: "O equilíbrio perfeito entre potência e finesse",
    description:
      "Pequena denominação de altíssima densidade qualitativa entre Pauillac e Margaux. Combina a estrutura do norte com a elegância do sul.",
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"],
    profile: "Cassis, cedro, tostado equilibrado. Harmonia clássica.",
    serveTemp: "17–18 °C",
    pairings: ["Carnes vermelhas", "Magret de pato", "Queijos curados"],
    aging: "12–35 anos.",
    topProducers: ["Léoville-Las Cases", "Ducru-Beaucaillou", "Beychevelle", "Gruaud-Larose"],
  },
  {
    slug: "medoc-haut-medoc",
    heroImage: "https://www.pichonbaron.com/image/images_site/1/accueil-background-site.jpg?1782288937",
    name: "Médoc & Haut-Médoc",
    bank: "Left",
    color: "Tinto",
    tagline: "A porta de entrada dos grandes tintos da margem esquerda",
    description:
      "As denominações regionais do Médoc reúnem excelentes tintos de Cabernet e Merlot, muitos com ótima relação preço-qualidade e alguns Crus Classés no Haut-Médoc.",
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot", "Cabernet Franc"],
    profile: "Frutas pretas, notas terrosas, taninos firmes porém acessíveis.",
    serveTemp: "16–18 °C",
    pairings: ["Ostras gratinadas", "Carnes grelhadas", "Queijos"],
    aging: "5–15 anos.",
    topProducers: ["La Lagune", "Cantemerle", "Sociando-Mallet"],
    qimoNote: "Denominação de Cussac-Fort-Médoc, onde acontece a degustação de ostras (Dia 2).",
  },
  {
    slug: "saint-emilion",
    heroImage: "https://www.saint-emilion-tourisme.com/media/cache/ogimage/uploads/img/saint-emilion-tourisme-com-65a161889c990278662155.jpg",
    name: "Saint-Émilion",
    bank: "Right",
    color: "Tinto",
    tagline: "O reino do Merlot, aveludado e generoso",
    description:
      "Na margem direita, sobre solos de calcário e argila, o Merlot e o Cabernet Franc dão tintos macios, perfumados e acessíveis quando jovens. Paisagem Patrimônio da UNESCO.",
    grapes: ["Merlot", "Cabernet Franc", "Cabernet Sauvignon"],
    profile: "Ameixa, cereja, trufa e violeta. Textura sedosa, taninos macios.",
    serveTemp: "16–18 °C",
    pairings: ["Cogumelos", "Aves", "Carnes em molho", "Queijos macios"],
    aging: "8–30 anos nos grandes crus.",
    topProducers: ["Cheval Blanc", "Ausone", "Figeac", "Angélus", "Pavie"],
    qimoNote: "Coração das experiências do Dia 5.",
  },
  {
    slug: "pomerol",
    heroImage: "https://www.moueix.com/sites/default/files/styles/hero_1280x1280/public/2021-07/slider_daccueil_photo_chai.jpg?itok=aF4MnGCU",
    name: "Pomerol",
    bank: "Right",
    color: "Tinto",
    tagline: "Merlot sublime sobre o 'boutonnière' de argila",
    description:
      "Minúscula denominação sem classificação oficial, mas com alguns dos tintos mais desejados e caros do mundo, graças ao terroir de argila azul de Pétrus. Perto de Libourne.",
    grapes: ["Merlot", "Cabernet Franc"],
    profile: "Trufa, ameixa cozida, chocolate e violeta. Opulência aveludada.",
    serveTemp: "16–18 °C",
    pairings: ["Pato", "Cordeiro", "Cogumelos e trufas"],
    aging: "10–40 anos.",
    topProducers: ["Pétrus", "Le Pin", "Vieux Château Certan", "Trotanoy"],
    qimoNote: "Vinhos escoados historicamente pelo porto de Libourne (Dias 5–6).",
  },
  {
    slug: "graves-pessac",
    heroImage: "https://www.smith-haut-lafitte.com/wp-content/uploads/2021/04/chateau-smith-haut-lafitte-yem.png",
    name: "Graves & Pessac-Léognan",
    bank: "Left",
    color: "Tinto/Branco",
    tagline: "O berço histórico do vinho de Bordeaux — tinto e branco",
    description:
      "Ao sul de Bordeaux, a única grande região que brilha tanto em tintos quanto em brancos secos de guarda. Solos de cascalho (graves) que deram nome à região. Abriga Haut-Brion.",
    grapes: ["Cabernet Sauvignon", "Merlot", "Sauvignon Blanc", "Sémillon"],
    profile: "Tintos defumados e minerais; brancos cítricos, encorpados e complexos.",
    serveTemp: "Tinto 17 °C · Branco 10–12 °C",
    pairings: ["Tinto: aves de caça", "Branco: peixes, ostras, aves"],
    aging: "Tintos 10–30 anos; grandes brancos 10–20 anos.",
    topProducers: ["Haut-Brion", "La Mission Haut-Brion", "Smith Haut Lafitte", "Domaine de Chevalier"],
  },
  {
    slug: "sauternes-barsac",
    heroImage: "https://www.yquem.fr/assets/og--ksNZ63V.jpeg",
    name: "Sauternes & Barsac",
    bank: "Sauternais",
    color: "Doce",
    tagline: "O ouro líquido — vinhos doces de podridão nobre",
    description:
      "Os mais célebres vinhos doces do mundo, nascidos da Botrytis cinerea que concentra as uvas nas manhãs de névoa do rio Ciron. Château d'Yquem é seu ápice absoluto.",
    grapes: ["Sémillon", "Sauvignon Blanc", "Muscadelle"],
    profile: "Mel, damasco, açafrão, casca de laranja confitada. Doçura equilibrada por acidez viva.",
    serveTemp: "8–10 °C (bem gelado)",
    pairings: ["Foie gras", "Queijo Roquefort", "Sobremesas de frutas", "Como aperitivo"],
    aging: "20–100 anos nas grandes safras.",
    topProducers: ["Château d'Yquem", "Climens", "Suduiraut", "Rieussec"],
    qimoNote: "Brinde no Château de Cadillac (Dia 3).",
  },
  {
    slug: "cotes-blaye-bourg",
    heroImage: "https://www.guide-bordeaux-gironde.com/_bibli/annonces/4674/hd/citadelle-de-blaye-spiritprod33-adobestock.jpg?v=preload",
    name: "Côtes de Blaye & de Bourg",
    bank: "Right",
    color: "Tinto/Branco",
    tagline: "Autenticidade e ótimo custo na margem direita",
    description:
      "As Côtes à beira do estuário produzem tintos redondos de Merlot e Malbec, além de brancos frescos. Terroirs generosos, honestos e acessíveis, com forte identidade local.",
    grapes: ["Merlot", "Cabernet Sauvignon", "Malbec (Côt)", "Sauvignon Blanc"],
    profile: "Frutas maduras, especiarias, taninos macios. Prontos para beber jovens.",
    serveTemp: "16–17 °C",
    pairings: ["Charcutaria", "Carnes grelhadas", "Pratos do dia a dia"],
    aging: "3–10 anos.",
    topProducers: ["Roc de Cambes", "Tayac", "Haut-Grelot"],
    qimoNote: "Denominações de Blaye e Bourg (Dia 4).",
  },
  {
    slug: "saint-estephe",
    heroImage: "https://www.estournel.com/wp-content/uploads/2025/05/Cos-dEstournel-Second-Cru-Classe-en-1855-a-Saint-Estephe.jpg",
    name: "Saint-Estèphe",
    bank: "Left",
    color: "Tinto",
    tagline: "O norte robusto do Médoc — firme e longevo",
    description:
      "A mais setentrional das grandes comunas do Médoc, com mais argila no solo, dá tintos poderosos, estruturados e de grande longevidade. Vizinha de Pauillac, ao norte da Route des Châteaux.",
    grapes: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"],
    profile: "Frutas pretas, notas terrosas e de couro, taninos firmes. Precisa de tempo.",
    serveTemp: "17–18 °C",
    pairings: ["Aves de caça", "Carnes vermelhas", "Queijos curados"],
    aging: "15–40 anos nas grandes safras.",
    topProducers: ["Cos d'Estournel", "Montrose", "Calon-Ségur", "Lafon-Rochet"],
    qimoNote: "Apelação vizinha de Pauillac, ao norte da rota do Médoc (Dia 2).",
  },
  {
    slug: "entre-deux-mers",
    heroImage: "https://www.chateau-cadillac.fr/var/cmn_inter/storage/images/_aliases/header_dropdown_image_webp/2/4/2/0/120050242-1-fre-FR/daa5381ab136-Chateau-Cadillac-c-CMN-visiter.webp.webp",
    name: "Entre-Deux-Mers",
    bank: "Entre-deux",
    color: "Branco",
    tagline: "Brancos secos e vivos entre dois rios",
    description:
      "A grande região verdejante entre a Garonne e a Dordogne, de colinas e bastides, é o berço dos brancos secos e frescos de Bordeaux — à base de Sauvignon Blanc, com Sémillon e Muscadelle.",
    grapes: ["Sauvignon Blanc", "Sémillon", "Muscadelle"],
    profile: "Cítrico, frutas brancas, toque herbáceo. Fresco, leve e vibrante.",
    serveTemp: "8–10 °C",
    pairings: ["Ostras e frutos do mar", "Peixes", "Saladas e queijos de cabra"],
    aging: "1–3 anos — beber jovem.",
    topProducers: ["Château Bonnet (André Lurton)", "Château Sainte-Marie", "Château Turcaud"],
    qimoNote: "A região dos brancos frescos — ideal com as ostras do roteiro.",
  },
];
