import { createRequire } from "module";
import { mkdirSync } from "node:fs";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PW || "playwright");
const SP = process.env.SHOTS || ".e2e-shots", base = process.env.BASE_URL || "http://localhost:3100";
mkdirSync(SP, { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push(`[pageerror] ${page.url()} ${e.message}`));
const login = async (name) => { await page.goto(base + "/login"); await page.getByText(name).click(); await page.waitForURL(base + "/"); await page.waitForTimeout(500); };
const check = async (label, cond) => console.log(cond ? "OK  " : "FAIL", label);
await login("Ana Martins");
let t = await page.locator("main").innerText();
await check("admin vê Comissão do mês", t.includes("Comissão do mês"));
await page.goto(base + "/seguradoras"); await page.waitForTimeout(700);
await page.screenshot({ path: `${SP}/d_seguradoras.png` });
await page.getByRole("button", { name: "Adicionar" }).click();
await page.getByPlaceholder("Ex.: Mitsui Sumitomo Seguros").fill("Mitsui Sumitomo Seguros");
await page.getByRole("dialog").getByRole("button", { name: "Auto", exact: true }).click();
await page.getByRole("dialog").getByRole("button", { name: "Salvar" }).click();
await page.waitForTimeout(400);
t = await page.locator("main").innerText();
await check("seguradora adicionada", t.includes("Mitsui Sumitomo Seguros"));
await page.goto(base + "/cotacoes/nova?ramo=auto&cliente=p-thiago"); await page.getByRole("button", { name: /Calcular em/ }).click(); await page.waitForURL(/\/cotacoes\/q-/, { timeout: 15000 }); await page.waitForTimeout(600);
t = await page.locator("main").innerText();
await check("multicálculo inclui manuais (Mapfre e Mitsui)", t.includes("Mapfre") && t.includes("Mitsui"));
await page.screenshot({ path: `${SP}/d_multicalculo.png`, fullPage: true });
await page.goto(base + "/configuracoes?aba=whatsapp"); await page.waitForTimeout(500); await page.screenshot({ path: `${SP}/d_whatsapp.png`, fullPage: true });
await page.goto(base + "/configuracoes?aba=retencao"); await page.waitForTimeout(500); await page.screenshot({ path: `${SP}/d_retencao.png`, fullPage: true });
for (const who of ["Carlos Lima", "Rafael Souza", "Marcos Teixeira"]) {
  await login(who);
  t = await page.locator("body").innerText();
  await check(`${who}: sem comissão no dashboard/menu`, !t.includes("Comissão do mês") && !/\nComissões\n/.test(t));
  await page.goto(base + "/comissoes"); await page.waitForTimeout(400);
  t = await page.locator("main").innerText();
  await check(`${who}: /comissoes bloqueado`, /permiss/i.test(t));
  await page.goto(base + "/cotacoes/q-thiago"); await page.waitForTimeout(500);
  t = await page.locator("main").innerText();
  await check(`${who}: sem coluna comissão no multicálculo`, !/comiss/i.test(t));
}
console.log(errors.length ? errors.join("\n") : "NO PAGE ERRORS");
await browser.close();
